### ISSUE TITLE
Need swagger-output.json in then callback instead of output file.

### ISSUE THREAD

**Issue by ahsan-javaid** [davibaltar/swagger-autogen#1]
swaggerAutogen generates swagger-output.json file, which is good. But there is no way to access this json in then response of swaggerAutogen function call. 

While you are resolving the promise in swaggerAutogen function please put the dataJSON variable  in second argument after true parameter. This will save the effort to read the swagger-output.json file.
Will be thankful if you can push this fix quickly.

**Comment by davibaltar** [comment]
Hello. It would be something like:

`return resolve ({success: true, data: dataJSON})`

at line 76 of the /swagger-autogen.js file

that right?

**Comment by ahsan-javaid** [comment]
Yes right.

**Comment by davibaltar** [comment]
Published. I changed the return to:

`return resolve ({success: true, data: objDoc})`

The "objDoc" is the final object before converting it to JSON.

**Comment by ahsan-javaid** [comment]
Thanks. It's working.
