### ISSUE TITLE
Add types to typescript

### ISSUE THREAD

**Issue by igorsilva3** [davibaltar/swagger-autogen#110]

**Comment by davibaltar** [comment]
Hi @igorsilva3. I didn't understand. Can you explain about this?

**Comment by igorsilva3** [comment]
Hi, @davibaltar. How are you?

Well, in a very simplified way, just add what are the modules, parameters and interfaces of the library.

That way I can get an idea of ​​what functions, interfaces your library can have and even more what parameters and their respective types a function requires.

Did you get it?

I'm not very good at explaining haha.

**Comment by davibaltar** [comment]
All good, @igorsilva3! And yes, I got it.

I have a code refactoring in my TODO list. But I'm gonna see the possibility to implement this features. 

Thanks for the suggestion!

**Comment by kleydon** [comment]
@davibaltar These links might be useful, re: a .d.ts "declaration" file, for swagger-autogen:

https://github.com/Microsoft/dts-gen
https://cameronnokes.com/blog/the-30-second-guide-to-publishing-a-typescript-package-to-npm/
