### ISSUE TITLE
Unhandled parsing case

### ISSUE THREAD

**Issue by ds-wb** [davibaltar/swagger-autogen#111]
When running node swagger.js I'm facing this :

```
/Users/dswb/Documents/git/backend/app/node_modules/swagger-autogen/src/handle-data.js:466
                    let auxBytePosition = auxData[idxPtn].split(']_])(')[1].split('([_[')[0].length;
                                                                           ^

TypeError: Cannot read properties of undefined (reading 'split')
    at /Users/dswb/Documents/git/backend/app/node_modules/swagger-autogen/src/handle-data.js:466:76
    at new Promise (<anonymous>)
    at Object.addReferenceToMethods (/Users/dswb/Documents/git/backend/app/node_modules/swagger-autogen/src/handle-data.js:406:12)
    at /Users/dswb/Documents/git/backend/app/node_modules/swagger-autogen/src/handle-files.js:262:38
```

I didn't took much time to investigate, but if I add a try/catch around the loop content, the fatal error become a warning, and as far as I can see the final swagger.json is generated perfectly, so I think that there's something specific to our project here...

Here are my changes : 
```
for (let idxPtn = 1; idxPtn < auxData.length; ++idxPtn) {
                    try {
                      let auxBytePosition = auxData[idxPtn].split(']_])(')[1].split('([_[')[0].length;
                      auxData[idxPtn] = auxData[idxPtn].replace(']_])(', `]_])([_[${bytePosition}]_])(`);
                      bytePosition += auxBytePosition;
                    } catch(e) {
                      console.log(e);
                    }
                }
```

instead of : 
```
for (let idxPtn = 1; idxPtn < auxData.length; ++idxPtn) {
                      let auxBytePosition = auxData[idxPtn].split(']_])(')[1].split('([_[')[0].length;
                      auxData[idxPtn] = auxData[idxPtn].replace(']_])(', `]_])([_[${bytePosition}]_])(`);
                      bytePosition += auxBytePosition;
                }
```

Just in case, I'm using node.js v17.0.1 / swagger-autogen 2.12.6 / macOS Monterey 12.1

Let me know if I can help to fix this at some point or if you need some other details

**Comment by davibaltar** [comment]
Hi @ds-wb! Thank you for opening the issue. 

I couldn't reproduce this problem here. Could you submit a sample project in your repository that reproduces this problem and send me the link, please? That way is easier to identify and fix the problem.

**Comment by ds-wb** [comment]
Hello @davibaltar. Thank to you for the reply and the work you are doing here !

Our project is private, and quite big with several hundreds .js files (without node modules). But I'll try to isolate the case and prepare something. Will keep you posted asap.

**Comment by ds-wb** [comment]
I think I found it :-)

We were using such lines in our main app.js : 
```
app.use('/countries', countryRouter);// this is a comment
```
If I just added a space before the comment mark, no more issue : 
```
app.use('/countries', countryRouter); // this is a comment
```
Not sure we need to ask ESlint to block such situations, or if you can do something, or both ?

Anyway hope that this can help!

**Comment by davibaltar** [comment]
Hi @ds-wb! Thank you for the feedback. 

I'll investigate this case and check if there is some thing I can do. Any other problems, let me know.

**Comment by davibaltar** [comment]
The version 2.18.0 has fixed some things about this.

Try with this version and if the problem persists, reopen the issue and let me know, please.

**Comment by ds-wb** [comment]
> The version 2.18.0 has fixed some things about this.
> 
> Try with this version and if the problem persists, reopen the issue and let me know, please.

I'm afraid to say that the problem persists with version 2.18.0 :(

**Comment by davibaltar** [comment]
Hi @ds-wb! :(

If you manage to post a small project that reproduces the error, maybe will be possible to identify the problem. If it is possible, let me know.

**Comment by ds-wb** [comment]
Hi @davibaltar 

Unfortunately I didn't succeed to reduce our big project to a significantly smaller one that keeps throwing the error... :(
On the other hand adding spaces before comment marks fix the issue for us.
I would suggest to close this issue until further notice (but keep it here for reference).

**Comment by davibaltar** [comment]
Ok @ds-wb, no problem. 

Thank you anyway.
