### ISSUE TITLE
Automatic Pattern Recognition - Regex Issue

### ISSUE THREAD

**Issue by DavidDunbier** [davibaltar/swagger-autogen#112]
Hi there, 

I ran into an issue with this project's handle-files.js, as some of my files being scanned ended up without any recognisable endpoints despite them completely identical swagger documentation.
I ended up delving into handle-files.js and tracing the issue back to the automatic pattern recognition to populate the patterns set. It turns out that the regex (at line 209) that transforms patterns into suitable objects for adding to the patterns set cannot account for when there is a comment immediately following the endpoint. When this happens, the semicolon will be added to the next pattern and it will incorrectly place the previous method's semicolon there, causing `;router` to be produced instead of `router`.

For example:

router.get(); //Comment -- This will work fine and produce `router` as expected
router.get();//Comment -- This will produce `;router` and cause everything following the semicolon to be ignored. 

This causes issues when the patterns are used later by addReferenceToMethods in handle-data.js, where references used to mark the endpoints are no longer added.

**Comment by davibaltar** [comment]
Hi @DavidDunbier! Thank you for opening the issue. 

Looking at line 209, a possible solution to this problem is to change the `';'` to `\;` in the regex:

Instead of: 
`.split(/\n|\s|\t|';'|\{|\}|\(|\)|\[|\]/)`

change to:
`.split(/\n|\s|\t|\;|\{|\}|\(|\)|\[|\]/)`

Could you test with this change and tell me if it works for you? Let me know if the problem persists or any other problem.

**Comment by DavidDunbier** [comment]
Hi there,

I tested with the change, but it didn't fix the issue.
With the limited troubleshooting I have done, I think it has something to do with the way the regex passed in (at line 208, defined on line ) is applied to the pattern, as the log for the pattern immediately after the regex is applied to it says that the pattern is unchanged.

My example output from logs:

Pattern: );router -- This is the listed pattern obtained from a generic example such as: router.get();//Comment

auxpattern: );router -- This is the pattern after the regex has been applied to it on line 208

auxpattern2 ,;router out -- This is the pattern after the above suggested modification for line 209, changing ';' to '\;'

auxpattern3 ;router out -- This is the final result pattern, which is then added back into the set of patterns at line 211

**Comment by davibaltar** [comment]
Thanks for the report, @DavidDunbier! 

I couldn't reproduce this problem. Could you submit in you repository a sample project that reproduces this problem and send me the link, please? 

That way is easier to identify and solve the problem.

**Comment by davibaltar** [comment]
The version 2.18.0 has fixed some things about this.

Try with this version and if the problem persists, reopen the issue and let me know, please.
