### ISSUE TITLE
Endpoints are not parsed if there are files and directories with same name

### ISSUE THREAD

**Issue by ASchwad** [davibaltar/swagger-autogen#114]
I just had the case that with unfortunate file namings, some endpoints where not parsed correctly (the routes where parsed correctly, but no swagger properties like req.body have been generated). We fixed it by restructuring our namings, nevertheless i wanted to share this issue as someone might find himself in the same situation.

Example setup:
We have a route middleware which describes multiple endpoints and the respective functions which are contained in a controller. The controller is imported like `const UserController = require('../controllers/user')`. Now there is a ambiguity for the `swagger-autogen` parser on how to resolve the path for the `UserController` as it could be either the `/user` directory or the `user.js` file.

Hierarchy:
```
/endpoints
 │  user.js
 │
 └─── /user
 │   │   lorem.js
 │   │   ipsum.js
```

Proposal on how to fix in `handle-files.js` - extend the exportPath with `.js` instead of `/index` in [line 693](https://github.com/davibaltar/swagger-autogen/blob/3f433e574335ab88b8b9eb545322c8cee244a50b/src/handle-files.js#L693):
```
// First, tries to find in the import/
idx = importedFiles.findIndex(e => e.varFileName && varFileName && e.varFileName == varFileName);
if (idx == -1) {
...                                    
} else {
  if (importedFiles[idx].isDirectory && !importedFiles[idx].isRequireDirLib) {
      exportPath = importedFiles[idx].fileName + '.js'; // instead of + '/index'
  }
}
```
@davibaltar If you'd like to, I can create a PR for this - but not sure which side effects this might have for other users.

**Comment by davibaltar** [comment]
Hi @ASchwad. Thanks for the report. 

About the [line 693](https://github.com/davibaltar/swagger-autogen/blob/3f433e574335ab88b8b9eb545322c8cee244a50b/src/handle-files.js#L693), I have a local set of tests that some projects need this line. But I would like to analyze your case to identify the difference. I couldn't reproduce this problem here. Do you have a simple project to submit with this problem? 

That way is easier to identify and try to fix it.

**Comment by davibaltar** [comment]
Hi @ASchwad! The version 2.18.2 has made some fixes about this. 

If the problem persists, let me know.
