### ISSUE TITLE
Performance issue with lookup for `res` and #swagger.auto

### ISSUE THREAD

**Issue by adrien-dorsaz** [davibaltar/swagger-autogen#115]
Hello !

My project is unable to generate documentation due to too long time to create the json file using swagger autogen 2.18.0 (around 20 minutes).

Recently, I added the description below outside a function to document a path in a centralized documentation file:

```
/*
  #swagger.start
  #swagger.path = '/accounting/exercises/opening_balance'
  #swagger.method = 'post'
  #swagger.security = [{bearerAuth:[]}]
  #swagger.summary = 'Create inital sold'
  #swagger.description = 'Create inital sold for each account of
    the balance sheet for the first exercise.'
  #swagger.tags = ['Exercises']
  #swagger.requestBody = {
    required: true,
    content: {
      'application/json': {
        schema: { $ref: "#/definitions/ExerciseOpeningBalance" },
      }
    }
  }
  #swagger.responses[200] = {
    required: true,
    content: {
      'application/json': {
        schema: { $ref: "#/definitions/ExerciseOpeningBalanceTransactions" },
      }
    }
  }
  #swagger.responses[401]
  #swagger.responses[422]
  #swagger.end
*/

```
As I'm using a centralized documentation file, I'm not able to include this definition inside the function.

I'll try as a workaround to add `#swagger.auto false` to my definitions as it seems the performance issue is due to automatic documentation lookup.

I'm opening this issue, because it was an interesting discover and I think it could impact other users.

I took a Performance map with the Chrome debugger and it seems the long time generation is due to this regular expression in [`src/handle-files.js#L1035`](https://github.com/davibaltar/swagger-autogen/blob/7250f6d49eac4beea1759b7bd85ea0eb4bf8ee48/src/handle-files.js#L1035):

```javascript
res = elemOrig.split(/([a-zA-Z]*|[0-9]|_|-)*\.status\(/);
```

At this point, I opened my debugger and I took the value of elemOrig and post it to [regex101](https://regex101.com/r/K3C92h/1) (see the `elemOrig` value at the end).

As you can see on regex101, this value of `elemOrig` raises a timeout while parsing the regexp.

I've tried these regexp and they solve the timeout issue, but I'm not sure of which one matches with the code intend:

* Remove star aside `[a-zA-Z]`, because the capturing group has already a star: `/([a-zA-Z]|[0-9]|_|-)*\.status\(/`
* Remove the star aside the capturing group because the code only lookup for `res[1]`: `/([a-zA-Z]*|[0-9]|_|-)\.status\(/`
* Remove the star aside the capturing group and allow every char to be repeated: `/((?:[a-zA-Z]|[0-9]|_|-)*)\.status\(/`
* Same idea with the shortcut [`\w`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes): `/((?:\w|-)*)\.status\(/`

Does this regexp try to retrieve a Javascript variable identifier using the `.status()` Express Response method ?

If that's the case, I think the latest regexp in the list above should work in a compatible way than current code.

Note, this Regexp could loose some valid identifiers and take some which are invalid, as you can see in the answers of this [StackOverflow post](https://stackoverflow.com/questions/1661197/what-characters-are-valid-for-javascript-variable-names).

----

`elemOrig` value causing issue:

> 
> /_undefined_path_0x2ac', 
>  #swagger.path = '/accounting/exercises/opening_balance'
>  #swagger.method = 'post'
>  #swagger.security = [{bearerAuth:[]}]
>  #swagger.summary = 'Create inital sold'
>  #swagger.description = 'Create inital sold for each account of
>  the balance sheet for the first exercise.'
>  #swagger.tags = ['Exercises']
>  #swagger.requestBody = {
>  required: true,
>  content: {
>  __¬¬¬__application/json__¬¬¬__: {
>  schema: { $ref: "#/definitions/ExerciseOpeningBalance" },
>  }
>  }
>  }
>  #swagger.responses[200] = {
>  required: true,
>  content: {
>  __¬¬¬__application/json__¬¬¬__: {
>  schema: { $ref: "#/definitions/ExerciseOpeningBalanceTransactions" },
>  }
>  }
>  }
>  #swagger.responses[401]
>  #swagger.responses[422]
> 
> __¬!@#$¬__FORCED__¬!@#$¬__

**Comment by davibaltar** [comment]
Hi @adrien-dorsaz! Thank you for opening the issue and for this report.

I'll analise the [src/handle-files.js#L1035](https://github.com/davibaltar/swagger-autogen/blob/7250f6d49eac4beea1759b7bd85ea0eb4bf8ee48/src/handle-files.js#L1035) and your code suggestion.

In the next version, I'll sumit a fix about this.

**Comment by davibaltar** [comment]
The version 2.18.4 has fixed this. But if the problem persists, let me know.

**Comment by adrien-dorsaz** [comment]
I've just tried the latest release. It works well, thanks !
