### ISSUE TITLE
Autogen fails with typescript

### ISSUE THREAD

**Issue by PauloFavero** [davibaltar/swagger-autogen#117]
Hi Davi, 

I am trying to add the swagger-autogen with typescript in this [repo ](https://github.com/rmanguinho/clean-ts-api/tree/fdf2751f989ecdbdfb2c36e64ff3708c4336fe67). This is a course that I am following. 

So, to add the swagger-autogen I created a swagger script 

```ts
import swaggerAutogen from 'swagger-autogen'

const outputFile = './doc/swagger-output.json'
const endpointsFiles = ['./src/main/config/routes.ts', './src/main/routes/**', './src/main/server.ts']

const doc = {
  info: {
    title: 'API',
    description: 'Swagger API'
  },
  host: `localhost:${process.env.PORT ? process.env.PORT : 3003}`,
  schemes: ['http'],
  consumes: ['application/json']
}

swaggerAutogen({ openapi: '3.0.0' })(outputFile, endpointsFiles, doc).then(async () => {
  await import('./src/main/server')
})
```

I modified this [file](https://github.com/rmanguinho/clean-ts-api/blob/fdf2751f989ecdbdfb2c36e64ff3708c4336fe67/src/main/config/config-swagger.ts)  to be like this:
```ts
import { serve, setup } from 'swagger-ui-express'
import swaggerConfig from '../../../doc/swagger-output.json'
import { noCache } from '../middlewares/no-cache'
import { Express } from 'express'

export default (app: Express): void => {
  app.use('/doc', noCache, serve, setup(swaggerConfig))
}
```

The routes are added in the router by these two files:

1.  [File 1](https://github.com/rmanguinho/clean-ts-api/blob/fdf2751f989ecdbdfb2c36e64ff3708c4336fe67/src/main/config/app.ts)
2.  [File 2 ](https://github.com/rmanguinho/clean-ts-api/blob/fdf2751f989ecdbdfb2c36e64ff3708c4336fe67/src/main/config/routes.ts)

I call this script with ts-node swagger.ts but it always fails. Is there a way I can run it in verbose mode or what could be going wrong?

**Comment by davibaltar** [comment]
Hi @PauloFavero! Thank you for opening the issue!

I'll check your case here as soon as possible and I''ll give you a feedback. About the verbose mode, the lib hasn't it, but I like this suggestion! I'll try to put it in the next version!

**Comment by davibaltar** [comment]
@PauloFavero, unfortunately swagger-autogen cannot interpret correctly your project, because the routes are defined at run-time, for example, in the code block:

```js
  app.use('/api', router)
  readdirSync(`${__dirname}/../routes`).map(async file => {
    if (!file.includes('.test.') && !file.endsWith('.map')) {
      (await import(`../routes/${file}`)).default(router)
    }
  })
```

the variable `file` in the map is defined only at run-time. Swagger-autogen does only the static analysis. But there are a way to workaround this declaring:

```js
import swaggerAutogen from 'swagger-autogen'

const outputFile = './doc/swagger-output.json'
const endpointsFiles = ['./src/main/routes/*']

...
```

And putting a `#swagger.path` tag at each endpoint, such as:

```js
export default (router: Router): void => {
  router.post('/signup', adaptRoute(makeSignUpController())
  // #swagger.path = "/api/signup"
  )

  router.post('/login', adaptRoute(makeLoginController())
  // #swagger.path = "/api/login"
  )
}

```

**Comment by PauloFavero** [comment]
Thanks Davi! It worked like a charm!
