### ISSUE TITLE
Duplicated params after the doc generation

### ISSUE THREAD

**Issue by PeterNgTr** [davibaltar/swagger-autogen#119]
I got an issue where params are duplicated after the doc generation.

![Screen Shot 2022-01-10 at 4 04 35 PM](https://user-images.githubusercontent.com/7845001/148788162-1c5c1f2c-5799-4852-8263-9033af3f6095.png)
![Screen Shot 2022-01-10 at 4 03 24 PM](https://user-images.githubusercontent.com/7845001/148788175-37e23863-567f-4e07-80f2-2223cad888e8.png)

**Comment by davibaltar** [comment]
Hi @PeterNgTr! Thank you for opening the issue.

Could you send me just this endpoint (the function that contain the `#swagger.parameters...`), please? 

That way is easier to identify and handle de problem.

**Comment by PeterNgTr** [comment]
![Screen Shot 2022-01-10 at 6 26 42 PM](https://user-images.githubusercontent.com/7845001/148810764-4363c87b-8eda-4f59-94f2-8d61e76d54d7.png)
hi @davibaltar my route looks like this.

**Comment by davibaltar** [comment]
@PeterNgTr, I've tried to reproduce this problem here, but I couldn't. Could you share your entire callback and the function `auth`, please? Or, if you have a project that reproduces this problem, send me the link, please.

**Comment by PeterNgTr** [comment]
hi @davibaltar thanks for prompt check. Here is my controller:

```
router.put('/merchant-users/:merchantUserId', auth, async function(req, res, next) {
    try {
        // #swagger.tags = ['Merchants']
        /*  #swagger.parameters['email_verification_sent'] = { in: 'body', type: 'object'} */
        res.json(await controller.updateMerxxxx(req.params.merchantUserId, req.body));
    } catch (err) {
        console.error(`Error: `, err.message);
        next(err);
    }
});
```

**Note**: if I pass my routes as an array, issue would occur.
```
app.use('/', [someRoutes, someRoutes2]);
```
If I pass the route individually, no issues 😅 
```
app.use('/', someRoutes);
app.use('/', someRoutes2);
```

**Comment by davibaltar** [comment]
Hi @PeterNgTr. I still couldn't reproduce this problem. But I have fixed somethings about duplicate parameters. Try with the version 2.18.7 and let me know if the problem persists, please.

**Comment by PeterNgTr** [comment]
hi @davibaltar 2.18.7 killed the issue. Thanks for your fix 😺
