### ISSUE TITLE
Intercept response and request?

### ISSUE THREAD

**Issue by maidul98** [davibaltar/swagger-autogen#12]
Sorry if this is a silly question but I was trying to figure out if this can simply just read the incoming and outgoing responses to construct the API doc similar to this: https://www.npmjs.com/package/express-oas-generator Can it do that? Or does it only interpret the comments and code? Thank you!

**Comment by davibaltar** [comment]
Hi @maidul98. 

Don't worry. Whenever you have any questions, you can ask. About your question, unfortunately the lib cannot do that. It only interprets comments and codes.
