### ISSUE TITLE
Suggestion: Separate DOCS page

### ISSUE THREAD

**Issue by developerphilo** [davibaltar/swagger-autogen#121]
I have really found this project worthwhile and fantastic over the last week.

I however was going through the README which is very great but found it hard navigation through the various sections.

I think having a separate DOCS page for this amazing project would be great for efficient navigation and maintenance.

What do you think about this? I would like to help setup the DOCS page if you in for the idea.

Thank you.

**Comment by davibaltar** [comment]
Hi @developerphilo! Thank you for opening the issue! 

Sorry for the delay in responding. DOCS page is a great idea! We can develop it. 

I'll do the initial setup as soon as possible, and after that, you can feel free to contribute.

Thanks!

**Comment by developerphilo** [comment]
Thank you for checking on this.
will be on the loop when the setup is ready.

**Comment by davibaltar** [comment]
Hi @developerphilo. Sorry for the delay. I've setup the GitHub Pages.

The docs will be stored in a separated branch (site): https://github.com/davibaltar/swagger-autogen/tree/site/docs

I put some files there just to test. But feel free to change the doc if you want. When the doc is ready, I will publish it.

Thanks!
