### ISSUE TITLE
errornous produces:[] generated

### ISSUE THREAD

**Issue by Ognian** [davibaltar/swagger-autogen#122]
Hi,
In one of my methods I have:
```
          res.setHeader('WWW-Authenticate', 'Basic realm="calendar access", charset="UTF-8"')
```
this leads that here:
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/1231174/149944777-27b682fd-674d-4958-99c9-08251a60c2bb.png">
an errornous produces:[] is generated:
<img width="445" alt="image" src="https://user-images.githubusercontent.com/1231174/149945148-02de796d-e490-49a1-a149-5601f59ea66e.png">

The problem is that openapitools/openapi-generator-cli generate is very upset:
```
Errors: 
        -attribute paths.'/CALENDARQUERIES/query/{calurlid}'(get).produces is unexpected
```

Any Ideas?

**Comment by davibaltar** [comment]
Hi, @Ognian! Thank you for opening the issue. 

I'll check this problem as soon as possible.

**Comment by davibaltar** [comment]
The version 2.19.0 has fixed a few things about this. Let me know if the problem persists.

**Comment by Ognian** [comment]
@davibaltar the new version fixed the problem.
Thanks a lot!
Ognian
