### ISSUE TITLE
Issue when router.js injects routers through the function

### ISSUE THREAD

**Issue by andyglez96** [davibaltar/swagger-autogen#126]
Hi guys, I'm trying to use this dependency to generate swagger in a NodeJS server with javascript and the router.js I point from the swagger.js as the "endpoint" file looks like this:

![image](https://user-images.githubusercontent.com/88163491/151646197-c0886899-996c-4e66-972b-cbcc8f0da9df.png)

The problem is the output generated looks like this:
![image](https://user-images.githubusercontent.com/88163491/151646208-cf4c6856-fde7-4451-adbd-36d81f7b2b73.png)

As you can see no path recognized

PS: when I import the routers into the route.js like i.e."src/campaign/campaign.router" works perfectly. The problem is inject the routers through the function

Any help will be much appreciated because I need to do it injjecting then the way is not working

Thanks in advance

**Comment by davibaltar** [comment]
Hi @andyglez96. Thank you for opening the issue. 

Sorry for the delay. If possible, could you submit a sample project that reproduces this problem and share the link? That way is easier to identify or handle the problem.

**Comment by ArnasJuskevicius** [comment]
Hello, @davibaltar 
I forked project and reproduced this issue. [Link to project](https://github.com/ArnasJuskevicius/example-swagger-autogen-with-router)

If you have idea where to start, let me know, I would gladly solve this issue and do PR.

**Comment by davibaltar** [comment]
Hi @ArnasJuskevicius! Sorry for the delay. 

The version 2.20.1 has fixed this. But if the problem persists, let me know.
