### ISSUE TITLE
can't recognize router using multiple middlewares.

### ISSUE THREAD

**Issue by dontbesatisfied** [davibaltar/swagger-autogen#128]
I'm using Nodejs 16.13 and typescript.

```
// can't find
router.use('/:apiKeyId/monitor', [checkApiKey], monitorRouter);

// find
router.use('/:apiKeyId/monitor', checkApiKey, monitorRouter);
```

**Comment by davibaltar** [comment]
Hi @dontbesatisfied! Thank you for opening the issue.

I've tried to reproduce this problem here but I couldn't. Could you submit a sample project that reproduces this problem and send me the link?

That way is easier to identify and fix the problem.

**Comment by davibaltar** [comment]
(Further information about my test)

I've tried with the following code: 

```js
router.get('/path', [func1], func2);

function func1(req, res, next) {
    try {
        // ...
        return next();
    } catch(err) {
         return res.status(501).send("...");
    }
}

function func2(req, res) {
    // ...
    return res.status(502).send("...")
}
```

and the result was as expected:

```json
    ...
    "/path": {
      "get": {
        "description": "",
        "parameters": [],
        "responses": {
          "501": {
            "description": "Not Implemented"
          },
          "502": {
            "description": "Bad Gateway"
          }
        }
      }
    },
    ...
```

Anything different you did, let me know.

**Comment by dontbesatisfied** [comment]
Thanks for reply :)

Did you tried using typescript?

**Comment by davibaltar** [comment]
Hi @dontbesatisfied. No, I didn't. But if you are using typescript, no problem, you can make a sample project using it. Thanks!

**Comment by davibaltar** [comment]
This issue will be handled in the #150.
