### ISSUE TITLE
Error when using tsconfig.json generated by npx tsc --init command.

### ISSUE THREAD

**Issue by matheusfenolio** [davibaltar/swagger-autogen#13]
I'm using the package with Typescript and it's working perfectly. But I found a little issue. When you generate the tsconfig file using "npx tsc --init" swagger-autogen cannot parse the JSON to an object due comments automatically inserted by generation.

![image](https://user-images.githubusercontent.com/37229507/105866820-2812f000-5fd3-11eb-8878-672c4498c870.png)

![image](https://user-images.githubusercontent.com/37229507/105866906-3cef8380-5fd3-11eb-99e4-c2a9b83f0cf6.png)

I don't know if there is a way to remove the comments when you parse. I case there isn't, should be great to add this information in documentation.

**Comment by davibaltar** [comment]
Hi @matheusfenolio. Thanks for opening the issue.  

Good to know about this! I've a function that remove all comments in the file. I can use it. Could you send me your tsconfig.ts file so that I can reproduce and handle the error here?

**Comment by matheusfenolio** [comment]
It worked perfectly! :smiley:

**Comment by davibaltar** [comment]
Great @matheusfenolio!! In the next version I'll submit this. 

Thank you!
