### ISSUE TITLE
Auto generated parameters duplicated with $ref parameters

### ISSUE THREAD

**Issue by samrensenhouse** [davibaltar/swagger-autogen#130]
Thanks for getting 2.19.0 out with the $ref parameters!

If I have a url defined like `/:someparam/endpoint` and a ref parameter setup like
```
 #swagger.parameters['$ref'] = ['#/components/parameters/someparam']
```

I will end up with a swagger.json like this:
```
{
    "name": "someparam",
    "in": "path",
    "required": true,
    "schema": {
        "type": "string"
    }
},
{
    "$ref": "#/components/parameters/someparam"
}
```
Ideally, I could override the automatically discovered parameters instead of both being generated. 
<br/>
<br/>
A simple solution might be to change this section to have the key be last element of parameter.split("/"): 
```
parameterObj.forEach((parameter, idx) => {
    objParameters[`$ref__¬¬__${idx}`] = {
        $ref: parameter
    };
});
```
But I imagine, it might work out better if instead it tries to do the deduplication later and uses the actual name field from the $ref parameter.

**Comment by davibaltar** [comment]
Hi @samrensenhouse! Thank you for the report.

I didn't pay attention to this case. And yes, using the actual name field in the `objParameters` it's a good idea. I'll fix it as soon as possible.

**Comment by davibaltar** [comment]
Hi @samrensenhouse!

The version 2.20.1 has fixed this. But if the problem persists, let me know.
