### ISSUE TITLE
Tags is not getting picked up

### ISSUE THREAD

**Issue by SirPhemmiey** [davibaltar/swagger-autogen#131]
Hey @davibaltar , good work on creating this package bro!

I'm having a weird issue though, some endpoints are not getting my tags while some are having it. What could be the issue here? Everything else is the same for both of them so i'm not sure why some are getting the tags/summary (as in `// #swagger.tags = ['SomeTag']`) and the others are not getting. Any lead or help would be appreciated. Thank you.

**Comment by davibaltar** [comment]
Hi @SirPhemmiey! Thanks! And thank you for opening the issue. 

To fix it, I need to be able to reproduce the problem here. In this case, could you submit a sample project the reproduces this problem and send me the link? That way is easer to identify and fix it.

**Comment by OmaHilde** [comment]
Hey @davibaltar , I assume that he is using an index.js and has two .js-files with identical endpoints. This is currently the issue in my case.
index.js
![image](https://user-images.githubusercontent.com/3921851/175002373-19d8cc1b-a9dd-4d0d-a966-c7417a32445f.png)
![image](https://user-images.githubusercontent.com/3921851/175002461-5ebaab10-d8fb-4e89-8e07-7455c6e4780c.png)

swagger-UI
![image](https://user-images.githubusercontent.com/3921851/175001995-a72fe398-e793-424a-8768-ba5d79ecb546.png)
The masterfehler IBN tag is missing the /setWrappingStillInProgress, even though it is tagged:
![image](https://user-images.githubusercontent.com/3921851/175002241-10fd6027-6299-45b0-9fa9-1429f938f1d7.png)

**Comment by OmaHilde** [comment]
Swagger-UI shows the issue
![image](https://user-images.githubusercontent.com/3921851/175004905-f55c6a83-e82b-4780-99fc-56368cedb992.png)
The route should be http://localhost:3000/masterfehler/IBN/auto

**Comment by OmaHilde** [comment]
Now it works. I had to only comment the routes in index.js with appropriate swagger-tags and now everything looks good. Issue is closed for me :) BTW @davibaltar , awesome work with this autogen, finding your project made my day big times!
![image](https://user-images.githubusercontent.com/3921851/175022110-79b75536-b64e-4bd2-b3fc-0e5474844524.png)

**Comment by davibaltar** [comment]
Hi @OmaHilde! Thank you for reopening the issue and posting your solution to the problem. This will help other people with the same problem. Issue is closed for me as well. Thanks!
