### ISSUE TITLE
When specificing components.schemas objects are duplicated

### ISSUE THREAD

**Issue by wizedkyle** [davibaltar/swagger-autogen#132]
When specifying components.schemas as per the the [OpenAPI 3.0.x specification](https://swagger.io/specification/) and running `npm run swagger-autogen` the following occurs:

Note: the swagger.js file is set with the following: `const swaggerAutogen = require('swagger-autogen')({ openapi: '3.0.2' })`

![image](https://user-images.githubusercontent.com/58360154/157226772-780c6517-dc0c-47c3-9a86-2c15daaff1ba.png)

![image](https://user-images.githubusercontent.com/58360154/157226847-f33ab103-c156-4bff-84b0-93dc02821d68.png)

However, if you just specify a single value without any properties the JSON file is rendered properly:

![image](https://user-images.githubusercontent.com/58360154/157227023-1324fdce-4214-4fb4-aac1-aa67c6ea4fa4.png)

![image](https://user-images.githubusercontent.com/58360154/157227075-00a78eb9-d0dc-4b87-9e3c-bb0e317d30e9.png)

**Comment by davibaltar** [comment]
Hi @wizedkyle. Thank you for opening the issue.

I couldn't reproduce this problem here. Could you submit a sample project that reproduces this problem and send me the link? That way is easier to identify and handle the problem.

**Comment by wizedkyle** [comment]
Hi @davibaltar,

I have created a small project here: https://github.com/wizedkyle/swagger-autogen-test which shows the problem.

Let me know if you need any further info.

**Comment by wizedkyle** [comment]
@davibaltar Just wondering if you were able to replicate the issue?

**Comment by wizedkyle** [comment]
Further testing looks like using `definitions` renders as `schemas` properly in `swagger-ui` however, definitions isn't technically in the 3.x.x spec as far as I know

![image](https://user-images.githubusercontent.com/58360154/158578563-59808277-a128-48bc-b169-a21c108f4dec.png)

**Comment by davibaltar** [comment]
Hi @wizedkyle. Sorry for the delay. The lib render automatically the schema. But when the render don't fit with the expected you can use the '@schema'. About your case, you can do it such as:

```js
const doc = {
    info: {
        version: '0.0.1',
        title: 'API',
        description: 'API Test'
    },
    components: {
        schemas: {
            test: {
                testProperty1: 123
            },
            test2: {
                testProperty2: 456
            }
        }
    }
}
```
NOTE: The '123' and '456' will make the render understand that it is a number type.

But maybe it's limited for your project. To workaround this, you can use the '@schema' in your endpoint, putting the specification swagger, for example:


app.get('/path', (req, res) => {
       ...
        /* #swagger.responses[200] = {
            description: 'description...',
            '@schema': {
                type: 'object',
                properties: {
                    testProperty1: {
                        type: 'integer',
                        format: 'int32',
                        description: 'test'
                    }
                }
            } 
        } */
       ...
})

For the next version, I will allow '@schema' in the 'doc', such as:

```js
const doc = {
    info: {
        version: '0.0.1',
        title: 'API',
        description: 'API Test'
    },
    components: {
        '@schemas': {
            test: {
                type: 'object',
                properties: {
                    testProperty1: {
                        type: 'integer',
                        format: 'int32',
                        description: 'test'
                    }
                }
            },
            test2: {
                type: 'object',
                properties: {
                    testProperty2: {
                        type: 'integer',
                        format: 'int32',
                        description: 'test'
                    }
                }
            }
        }
    }
}
```
Thus, won't render the the schemas and put in the .json like declared in the '@schemas'

And thanks, because seeing your sample project I identified that this last case is not working and identify some bugs as well. 

If I haven't fully answered your question, please let me know.

**Comment by wizedkyle** [comment]
@davibaltar Thank you for the response that answers my question.

For the moment I will use the `definition` field while the next version is worked on.

**Comment by davibaltar** [comment]
Hi @wizedkyle!

The version 2.20.0 has fixed this. In your case, you can use the `@schemas` properties so that swagger-autogen doesn't render the schemas, such as:

```js
const doc = {
    ...
    components: {
        '@schemas': {
            test: {
                type: 'object',
                properties: {
                    testProperty1: {
                        type: 'integer',
                        format: 'int32',
                        description: 'test'
                    }
                }
            },
            test2: {
                type: 'object',
                properties: {
                    testProperty2: {
                        type: 'integer',
                        format: 'int32',
                        description: 'test'
                    }
                }
            }
        }
    }
}
```

But if the problem persists, let me know.

**Comment by wizedkyle** [comment]
@davibaltar This works perfect now, thank you for fixing this.
