### ISSUE TITLE
Issue auto generated with router

### ISSUE THREAD

**Issue by sam5727** [davibaltar/swagger-autogen#133]
Thanks for your work! I'm having an issue with sth like
```ts
    const router = express.Router();
    router.use("/v1", r1);
    router.use("/v2", r2);
    app.use("/api", router);
    app.use('/doc', swaggerUi.serve, swaggerUi.setup(swaggerFile));
```

But `paths` in generated swagger_output.json do not contain prefix `/api`
It shows `/v1/...` instead of `/api/v1/...`

**Comment by jeanbmar** [comment]
I've had similar issues using .mjs files with ESM modules.
It could be a nice addition to this module to reverse the list of routes from the `app` instance instead of parsing them from files.

**Comment by davibaltar** [comment]
Hi there! Thank you for opening the issue, @sam5727.

Yes, the lib still doesn't recognize this case. But I will add it in my TODO list here and try to add it in the next versions.

**Comment by davibaltar** [comment]
Hi guys! The version 2.20.2 has fixed somethings about this. 

If the problem persists, let me know.
