### ISSUE TITLE
Issue auto generated without router

### ISSUE THREAD

**Issue by sam5727** [davibaltar/swagger-autogen#134]
Thanks for fixing #133, but I think it causes another issue like

```
    const router = express.Router();
    router.use("/v1", r1);
    router.use("/v2", r2);
    app.use("/api", router);
    app.get("/ver", ...)
    app.use('/doc', swaggerUi.serve, swaggerUi.setup(swaggerFile));
```
It shows `/api/ver` instead of `/ver`

**Comment by davibaltar** [comment]
Hi @sam5727! Thank you for this report. 

I'll fix it as soon as possible.

**Comment by davibaltar** [comment]
The version 2.20.6 has fixed somethings about this. If the problem persists or if you find any other problem, let me know.
