### ISSUE TITLE
[Typescript] Query capture breaks when the type of the parameters is express.X

### ISSUE THREAD

**Issue by BastienGarcia** [davibaltar/swagger-autogen#135]
When adding routes to a router, automatic captures of query parameters (and annotations) seems to break if req is of type express.Request

```TSX
import express from 'express';
const router = express.Router();

router.get('/query-success', (req: any, res: any) => {
  // #swagger.description = desc
  res.send(req.query.obj);
});
router.get('/query-fail', (req: express.Request, res: any) => {
  // #swagger.description = desc
  res.send(req.query.obj);
});
```

Output: 
![image](https://user-images.githubusercontent.com/55688009/160401596-21f9af02-abd1-4a83-a547-a3bfda3a7dc3.png)

As a workaround, I found that directly importing the Request type from express and using that instead works fine.

```TSX
import express, { Request, Response } from 'express';
const router = express.Router();

router.get('/query-fail', (req: Request, res: Response) => {
  // #swagger.description = desc
  res.send(req.query.obj);
});
```

Output: 
![image](https://user-images.githubusercontent.com/55688009/160402088-9a1005fa-679e-4c41-9d02-27535a7aed70.png)

**Comment by davibaltar** [comment]
The version 2.20.6 has fixed somethings about this. If the problem persists, let me know.
