### ISSUE TITLE
Uso dos comentários não funciona bem usando classes e async juntos no typescript

### ISSUE THREAD

**Issue by Hilson-Alex** [davibaltar/swagger-autogen#136]
Estive tentando usar o autogen para gerar a documentação do swagger, mas quando passava callbacks ao invés de funções para um router, como no exemplo abaixo, os comentários da função não eram reconhecidos.

```node
    constructor() {
        // this.router = Router()
        this.router.get('/', middleware, this.getAll);
    }

    private async getAll (req: Request, res: Response) {
        /*
           #swagger.tags = ['ReferralService']
           #swagger.description = 'Endpoint para recuperar todos os serviços de referencia'
           #swagger.security = [{
                "ApiKeyAuth": []
            }]
        */
        return res.status(HttpStatus.OK).send({message: 'respond with a resource'})
    }
````

Enquanto ao passar a função diretamente para o router como função anônima, funcionava corretamente:

```node
        this.router.get('/', middleware, async (req: Request, res: Response, next: Function) => {
             /*
                #swagger.tags = ['ReferralService']
                #swagger.description = 'Endpoint para recuperar todos os serviços de referencia'
                #swagger.security = [{
                     "ApiKeyAuth": []
                 }]
             */
             return res.status(HttpStatus.OK).send({message: 'respond with a resource'})
         })
```

Ao investigar o seu código, identifiquei duas causas para isso:

1. no método `functionRecognizerInData`, ao tentar recuperar essa função, estava sendo passado o `this`, e não o nome da função.
2. na função `clearData` tem a seguinte linha: `aData = aData.replaceAll(' async ', '');`

O problema no primeiro caso é óbvio: A função `this` não é encontrada no arquivo, e por isso os comentários não são considerados. consegui contornar isso usando `const getAll = this.getAll` dentro do construtor, e isso me levou ao segundo problema.

Ao dar um replace em `' async '`, a minha função se transforma em `privategetAll`, o que também faz com que ela não seja encontrada pela sua função `functionRecognizerInData`, e por isso os comentários também não são considerados.

**Comment by davibaltar** [comment]
@Hilson-Alex, a versão 2.20.7 fez algumas correções sobre isso. Se o problema persistir, me fala, por favor.
