### ISSUE TITLE
Authorize button appear on default

### ISSUE THREAD

**Issue by weihan1394** [davibaltar/swagger-autogen#14]
Hi, 

I could not find from the github readme on how I can remove the authorize button. Is there anyway I can define in the docs to remove the button?

![image](https://user-images.githubusercontent.com/7189650/106010999-0578f800-60f5-11eb-9878-7db5c6d77b19.png)

**Comment by davibaltar** [comment]
Hi @weihan1394. Thank you for opening the issue. 

I'll remove the button if the "securityDefinitions" parameter is missing or it is equal to {}. I'll try to submit this in the next version. I believe it won't be long.

**Comment by weihan1394** [comment]
Hi @davibaltar Thank you for the quick response. Looking forward to the next version! :)

**Comment by davibaltar** [comment]
Hi @weihan1394. This issue was handled in version 2.5.9. But if the problem persistis, let me know.
