### ISSUE TITLE
Lib doesn't seem to read routes file

### ISSUE THREAD

**Issue by bralandealmeida** [davibaltar/swagger-autogen#140]
Hello there,

I'm trying to add express routes in swagger but for some reason the file is not read. Am I doing something wrong?

Some time ago I did a test and it seems to work well. But in this other folder organization model, the lib doesn't seem to work. @davibaltar would you help me?

The repository with the projects is in this link: https://github.com/bralandealmeida/swagger-example, and the model I'm referring to doesn't work is the one inside the TS folder.

**Comment by davibaltar** [comment]
Hi @bralandealmeida! Thank you for opening the issue.

I'll fix it as soon as possible.

**Comment by davibaltar** [comment]
The version 2.21.0 has fixed this. If the problem persists, let me know.

**Comment by bralandealmeida** [comment]
> 

It's a bit of a strange behavior. I literally copied the `swagger.js` you mentioned and I still couldn't generate the routes that are inside the test project's routes file. Only the route that is inside the server.

I tried with the typescript and with the build version. No success with any. I updated the example repository again.

**Comment by davibaltar** [comment]
Thank you, I'll see it. And just to know, what OS and NodeJS version are you using?

**Comment by bralandealmeida** [comment]
> Thank you, I'll see it. And just to know, what OS and NodeJS version are you using?

I'm using macOS 12.3.1 and NodeJS 16.13.

**Comment by davibaltar** [comment]
Sorry for the delay. I'm using macOS 10.14.6 and NodeJS 12.13.0. Any news, I'll post here.

**Comment by bralandealmeida** [comment]
I've tried to change the Node version to the same as yours, but with no success. I will also analyze and post any news here.

**Comment by bralandealmeida** [comment]
I think I may have understood the problem. When the lib reads the routes file inside `./src/shared/infra/routes/index.ts` it is generating a wrong filepath of these routes, see:

```
./src/shared/infra/http/routes/modules/test/infra/routes/test.routes.ts
/Volumes/Slim/Projetos/community/swagger-autogen/src/handle-files.js:32
            console.log(data.trim());
                             ^

TypeError: Cannot read properties of undefined (reading 'trim')
    at ReadFileContext.callback (/Volumes/Slim/Projetos/community/swagger-autogen/src/handle-files.js:32:30)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:314:13)
error Command failed with exit code 1.

```

The correct path of the `test.routes.ts `file would be `./src/modules/test/infra/routes/test.routes.ts` and not the one he's trying to find.

**Comment by bralandealmeida** [comment]
Another point is that she is not being able to understand the extension of this file when calling the readEndpointFile function.

```
./src/shared/infra/http/routes/modules/test/infra/routes/test.routes
/Volumes/Slim/Projetos/community/swagger-autogen/src/handle-files.js:31
            console.log('filePath', data.trim());
```
In the previous comment I had forced the extension on this line:

https://github.com/davibaltar/swagger-autogen/blob/085be9ee4229dfbddf16bf14ba8bb9bff5b0bfa4/src/handle-files.js#L1723

**Comment by davibaltar** [comment]
Hi @bralandealmeida! Thanks a lot for the PR. I've merged and I only made an adjustment at the line:

`let baseUrl = tsBaseUrl && tsBaseUrl.split('/').length > 1 ? tsBaseUrl.split('/')[1] + '/' : './';`

The `tsBaseUrl.split('/').length > 1` avoid when tsconfig.json file constains for example `"baseUrl": "."` generate a `baseUrl` equals `'undefined/'`. 

The version 2.21.1 contains your code. Any problems, let me know.

**Comment by bralandealmeida** [comment]
> Hi @bralandealmeida! Thanks a lot for the PR. I've merged it and I only made an adjustment at the line:
> 
> `let baseUrl = tsBaseUrl && tsBaseUrl.split('/').length > 1 ? tsBaseUrl.split('/')[1] + '/' : './';`
> 
> The `tsBaseUrl.split('/').length > 1` avoid when tsconfig.json file constains for example `"baseUrl": "."` generate a `baseUrl` equals `'undefined/'`.
> 
> The version 2.21.1 contains your code. Any problems, let me know.

Awesome! Works perfectly!
