### ISSUE TITLE
Description format

### ISSUE THREAD

**Issue by akhayyat** [davibaltar/swagger-autogen#144]
Can endpoint description (`#swagger.description`) contain multiple paragraphs and other formatting structures (pre-formatted, code, bold, italics)? It'd be great if it can be written using markdown, for example.

Some endpoints require long, multi-paragraph descriptions.

**Comment by davibaltar** [comment]
Hi @akhayyat! The swagger description accept HTML tags. You can use them to format your description. About accept markdown, this is not in the scope of the swagger-autogen, because it only generate the .json file.
