### ISSUE TITLE
Adding swagger tag in express.Router middleware

### ISSUE THREAD

**Issue by Fisher-Rachel** [davibaltar/swagger-autogen#146]
I'm trying to add a tag in the middleware of express.Router but it isn't generated:
```
const express = require('express');
const router = express.Router();

router.use((_req, _res, next) => {
     // #swagger.tags = ['Tag']
      return next();
 });

router.get('/', controller.find);
router.post('/', controller.add);
router.put('/:id', controller.update);
```
However, when I'm adding the middleware to a specific route the tag is generated:
```
const express = require('express');
const router = express.Router();

const swaggerMiddleware = (_req, _res, next) => {
     // #swagger.tags = ['Tag']
      return next();
 };

router.get('/', swaggerMiddleware, controller.find);
router.post('/', swaggerMiddleware, controller.add);
router.put('/:id', swaggerMiddleware, controller.update);
```
Is there a way to add the tag in the router level so I don't have to add it specifically to each route?

**Comment by davibaltar** [comment]
Hi @Fisher-Rachel. Thank you for opening the issue. 

This is a bug. I'll fix it. After the fix, it will be possible declare tags like you did in the first case.

**Comment by davibaltar** [comment]
The version 2.21.2 has fixed this. If the problem persists, let me know.
