### ISSUE TITLE
File upload with OpenAPI 3.0

### ISSUE THREAD

**Issue by PauloFavero** [davibaltar/swagger-autogen#147]
Hi Davi,

I'm using swagger-autogen with the openAPI 3.0. 
I have a route that should upload multiple XML files and I noticed that the multer upload example only works with OpenAPI 2.0. 
I tried to modify the swagger comments to meet the [specification 3.0](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#considerations-for-file-uploads) but I didn't have success.

Is it something that has not yet been implemented or I'm doing something wrong?

Thanks in advance

Endpoint documentation:

```typescript
export default (router: Router): void => {
  router.post(
    '/mes/config',
    adaptMulter,
    adaptRoute(makeUploadConfigController())
    /*
      #swagger.tags = ['Test']
      #swagger.summary = 'Endpoint to upload multiple config files'
      #swagger.description = 'Config files'
      #swagger.path = "/api/mes/config"
      #swagger.consumes = ['multipart/form-data']
      #swagger.produces = ['application/json']
      #swagger.parameters['multFiles'] = {
          in: 'formData',
          type: 'array',
          required: true,
          description: 'config files',
          collectionFormat: 'multi',
          items: {
            type: 'string',
            format: 'binary'
           }
      }
      #swagger.responses[200] = {
          description: 'Configuration sent',
      },
      #swagger.responses[400] = { description: 'Invalid params' }
      #swagger.responses[500] = { description: 'Internal Server Error' }
  */
  )
}
```

The generated swagger output is:

```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "External Provider API",
    "description": "API to manage external providers",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://10.0.0.168:5000"
    },
    {
      "url": "http://localhost:5000"
    },
    {
      "url": "http://localhost:5000"
    }
  ],
  "paths": {
    "/api/mes/config": {
      "post": {
        "tags": [
          "MES"
        ],
        "summary": "Endpoint to upload multiple CONFIG files",
        "description": "CONFIG files",
        "parameters": [
          {
            "name": "multFiles",
            "in": "formData",
            "required": true,
            "description": "CONFIG files",
            "collectionFormat": "multi",
            "items": {
              "type": "string",
              "format": "binary"
            },
            "schema": {
              "type": "array"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Configuration sent"
          },
          "400": {
            "description": "Invalid params"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    }
  }
}

```

**Comment by BastienGarcia** [comment]
Not sure if you can do it only using comments right now, but defining components manually lets you achieve what you want.
```
// Add to the `doc` you pass as argument to swagger-autogen
    components: {
      '@schemas': {
        Medias: {
          type: 'object',
          properties: {
            multFiles: {
              type: 'array',
              items: {
                type: 'string',
                format: 'binary',
              },
            },
          },
        },
      },
    },```
You can then reference that schema in your route / router
```
  router.post('/mes/config', () => {
    /*
      #swagger.tags = ['Test']
      #swagger.summary = 'Endpoint to upload multiple config files'
      #swagger.description = 'Config files'
      #swagger.path = "/api/mes/config"
      #swagger.produces = ['application/json']
      #swagger.requestBody = {
        required: true,
        description: 'config files',
        content: {
          "multipart/form-data": {
            schema: { $ref: "#/definitions/Medias" }
          }
        }
      }
      #swagger.responses[200] = {
          description: 'Configuration sent',
      },
      #swagger.responses[400] = { description: 'Invalid params' }
      #swagger.responses[500] = { description: 'Internal Server Error' }
  */
  });
```
Example output:
![image](https://user-images.githubusercontent.com/55688009/172031881-57ff3413-b739-460f-bad3-db9b77bbc5f5.png)

**Comment by davibaltar** [comment]
Hi, @PauloFavero! Thank you for opening the issue. 

I don't know any other solution besides the one shown by @BastienGarcia. If it doesn't work for your project, let us know.

**Comment by davibaltar** [comment]
Closing the issue. Thank you for the answer @BastienGarcia!
