### ISSUE TITLE
Promises resolving into routers/middlewares prevents detection

### ISSUE THREAD

**Issue by BastienGarcia** [davibaltar/swagger-autogen#148]
Language: Javascript/Typescript
Package version: swagger-autogen@2.21.2
[Reproducible example](https://github.com/BastienGarcia/example-swagger-autogen-async-issues)
Might be somewhat related to #79 

When using an async function to generate middlewares or a router, definitions inside that function are not properly generated. For example, the routes defined in the following router are not detected at all.
```
  const app = express()

  /* Routes */
  // require('./routes') is a promise
  const router = await require('./routes')

  /* Middlewares */
  app.use(router)
  app.use('/doc', swaggerUi.serve, swaggerUi.setup(swaggerFile))

  return app;
```

Removing the `await` keyword from the sources in some cases seems to fix generation, although this results into invalid code. However, filtering out the `await` keyword while parsing files in swagger-autogen seems to cover most uses of promises.
I tried to implement a possible implementation of this solution/workaround (See `src/removeAwaits.js` in reproducible example). I've also done some basic tests in `routes.js` to make sure the implementation works.
```
    const router = express.Router()

    const apiV1 = require('./controllers/ApiRoute1');
    const apiV2 = require('./controllers/ApiRoute2');

    // The following tests cover multiple use cases with promises/await
    // Await in the method
    router.use('/inline',     await      apiV2);
    // Await reassigned promise
    const reassignedInline = apiV2;
    router.use('/inline/reassigned', await reassignedInline);
    // Awaited require
    router.use('/inline/require', await require('./controllers/ApiRoute2'));
    // Await in var
    const routes =     await    apiV2;
    router.use('/var', routes);
    // Awaited promise
    const awaited = await require('./controllers/ApiRoute2');
    router.use('/awaited', awaited);
    // Reassigned awaited
    const reassigned = awaited;
    router.use('/awaited/reassigned', reassigned);
    // Promise (not handled)
    await apiV2.then((promisedRoutes) => {
        router.use('/promise', promisedRoutes)
    })
    // Promise.all (not handled)
    await Promise.all([apiV2, new Promise(resolve => setTimeout(resolve, 1))]).then((promisedRoutes) => {
        router.use('/promise/all', promisedRoutes[0]);
    });

    // The following tests make sure that removeAwaits() works safely (don't delete in string/comments)
    // Comment with the word "await"
    router.get('/safe-replace/comment', (req, res) => {
        // #swagger.description = "This comment should keep the word ' await ' and not parse it out"
        res.send('');
    });
    // String with the word "await"
    router.get('/safe-replace/string', express.json(), (req, res) => {
        console.log("` await ");
        console.log(`' await `);
        console.log("\" await ");
        res.send('" await ');
    });
```
If this solution looks interesting to you, I can try to implement the last missing use cases, optimize it and/or more properly document it.
If this solution isn't what you would be looking for, I am also available to provide more examples of possible usages of promises.

**Comment by davibaltar** [comment]
Hi, @BastienGarcia! Thank you for opening the issue and thanks a lot for the proposed solution. 

I'm taking a look at it and I have just one thing to improve it. Instead of:

```js
if (data.slice(idx, idx + 6) === 'await ') {
```

Change to:
```js
if (data.slice(idx, idx + 6) === 'await ' && idx > 0 && data[idx - 1].split(new RegExp("([a-z]|[A-Z]|[0-9]|_|$)")).length === 1) {
```

This avoid variables that contain `await` at the end of them from being changed, for example: 

```js
    const apiV1 = require('./controllers/ApiRoute1');
    const apiV1await = require('./controllers/ApiRoute2');
```

In the above case, the `await` in `apiV1await` won't be removed. 

Please, submit it for us. My suggestion it is put the function in the `./src/handle-data.js` file and call it at the end of the method `clearData` (that also is in the handle-data.js file). Note: The method `clearData` has the purpose to remove somethings so that the data be ready to be parsed.

**Comment by davibaltar** [comment]
Hi @BastienGarcia. I've changed a few things in the removeAwaits function, such as:

- Removal of `idx -= 1`. Doing some testing here this was not necessary, but please, let me know if this causes any problems in your case. Here I had no problems after removing it.
- Adaptation of `idx += 1` inside `for`. Changing the `idx` variable inside `for` can put `for` in an unstable situation. I made some changes to adapt and have the same result.
- Added `try..catch`
- Use the same function to remove `async` keywords as well.
- Changes required by eslint.


The version 2.21.3 has implemented it. Any problems, let me know. Thanks!
