### ISSUE TITLE
Doc Expansion in autogen

### ISSUE THREAD

**Issue by nil1729** [davibaltar/swagger-autogen#15]
How can I default hide expansion for all tags using swagger-autogen? Like this attached image.
![Screenshot from 2021-01-29 21-25-38](https://user-images.githubusercontent.com/54589036/106297371-a17f3c80-6278-11eb-97ca-0a5823a0906d.png)

**Comment by davibaltar** [comment]
Hi @nil1729. You can do this passing the parameter **docExpansion = 'none'** in the middleware of swaggerUI, like:

```
const swaggerUi = require('swagger-ui-express')
const swaggerFile = require('./swagger_output.json')
const express = require('express')
const app = express()

app.use('/doc', swaggerUi.serve, swaggerUi.setup(swaggerFile, false, { docExpansion: "none" }))
```

if you succeed, let us know.

**Comment by nil1729** [comment]
Thank you so much @davibaltar for your reply. It's working.

**Comment by sofian-sd** [comment]
Hi, thanks for the response !
I have another question concerning the docExpansion.
If i the option argument is not false, the docExpansion is not triggered, is it normal ?

This is working
`app.use('/doc', swaggerUi.serve, swaggerUi.setup(swaggerFile, false, { docExpansion: 'none' }));`

In this case, the customCss is applied but the docExpansion is not. 
`app.use('/doc', swaggerUi.serve, swaggerUi.setup(swaggerFile, { customCss: '.swagger-ui .topbar { display: none }' }, { docExpansion: 'none' }));`

Is it an issue or i miss something ?

Thanks.

**Comment by maykonpaulo** [comment]
Hy @sofian-sd ...

Your question has been around for a long time. I imagine I've already found the answer, but since someone else might have the same question, here's the solution:

`app.use('/doc', swaggerUi.serve, swaggerUi.setup(swaggerFile, { customCss: '.swagger-ui .topbar { display: none }', swaggerOptions: { docExpansion: "none" } });`
