### ISSUE TITLE
TypeError: jsParsed.variablesfilter is not a function

### ISSUE THREAD

**Issue by ticklewind** [davibaltar/swagger-autogen#154]
version 2.21.4

**Comment by davibaltar** [comment]
Hi @ticklewind. Thank you for opening the issue. 

Could you specify which file and line this happened? If possible, post the full stack trace, please.

**Comment by Ruekov** [comment]
Hey Davi, I have the same issue.  In my case the full error stack in my case is this one:

```
.\node_modules\swagger-autogen\src\handle-files.js:1029
                                    let found = jsParsed.variablesfilter(v => v.name == _return && v.end <= bytePosition);
                                                         ^
TypeError: jsParsed.variablesfilter is not a function
    at .\node_modules\swagger-autogen\src\handle-files.js:1029:58
```

In my case I downgraded to v.2.8.2 to avoid the problem.  If you need anything else I will answer you ASAP.

-Regards!

**Comment by lucasmombello** [comment]
Same issue here on  swagger-autogen@2.21.4
![image](https://user-images.githubusercontent.com/76074491/177278856-722494b7-f4cd-4cf8-bd9c-efefbcbaa890.png)

**Comment by deborahbruna** [comment]
Same problem here! 
version 2.11.2!
v2.8.2 works. Thanks @Ruekov 

<img width="765" alt="image" src="https://user-images.githubusercontent.com/33626483/177321988-7c016407-3874-4e83-a8a1-2ec1bfac4602.png">

**Comment by drecchia** [comment]
Its happens if you try to use return inside of the middleware, using vars to isolate logic is an workaround.

Example of statements with error:
`return res.status(200).send([]);`
