### ISSUE TITLE
How to properly use multiple parameters?

### ISSUE THREAD

**Issue by ncesar** [davibaltar/swagger-autogen#157]
Hi, i'm trying to use the multiple parameters with openapi 3.0 but I'm receiving this error: 
![image](https://user-images.githubusercontent.com/29064514/177703195-1e69d3d9-d80a-4a2a-8689-4ad729b07463.png)

This is how I'm using it in my routes file: 
![image](https://user-images.githubusercontent.com/29064514/177703250-03df77c4-4689-4007-ad85-fe687d9ab522.png)
`/*  #swagger.parameters['$ref'] = ['#/components/parameters/errorMessage', '#/components/parameters/sessionId']` */`

And this is my swagger.ts file: 
![image](https://user-images.githubusercontent.com/29064514/177703284-af158c30-594e-4f19-bde5-5ef085b31e4d.png)

What I'm doing wrong?

**Comment by davibaltar** [comment]
Hi @ncesar! Thank you for opening the issue. 

In your case, you must to declared your `errorMessage` and `sessionId` in the swagger.ts file, such as:

 ```js
...
components: {
    parameters: {
        errorMessage: "some thing... It can be an object, array, number or boolean as well",
        sessionId: "some thing... It can be an object, array, number or boolean as well",
        ...
    }
}
```

If the problem persists, post your .json output file, please. That way is easier to identify and fix it.

**Comment by ncesar** [comment]
thank you @davibaltar
