### ISSUE TITLE
#swagger.ignore break in 2.21.1

### ISSUE THREAD

**Issue by balouk** [davibaltar/swagger-autogen#158]
We use swagger.ignore for some endpoints, and for some reason it doesn't work anymore.

`exports.quotation = async (req, res, next) => {
  // #swagger.ignore = true
};`

I downgrade to 2.21.0 to fix this.

**Comment by davibaltar** [comment]
Hi @balouk. Thank you for opening the issue. 

Could you send a sample project that reproduces this problem? That way is easier to identify and fix the problem.

**Comment by davibaltar** [comment]
Hi @balouk! Sorry for the delay. 

Thank you for sending the sample code. I'll take a look and try to fix it as soon as possible.

**Comment by clementdelannoy** [comment]
Hi ! Same thing on 2.21.0 and 2.21.5, `// #swagger.ignore = true` doesn't work for me.

**Comment by davibaltar** [comment]
Hi there! 

The version 2.21.6 has fixed this. But if the problem persists, let me know.
