### ISSUE TITLE
Error when moving swagger.ts to a nested folder

### ISSUE THREAD

**Issue by ncesar** [davibaltar/swagger-autogen#159]
Hi!

I was using the extension and it looks very good so far, thanks for your work Davi!
The problem I'm facing is that everytime I move the swagger.ts file to a directory like src/swagger/swagger.ts, it will always complain about the endpoint file returning not found.

See my structure following the example-swagger-autogen-with-router:
![image](https://user-images.githubusercontent.com/29064514/178163576-50e94fc7-2822-4990-8b65-2f217dc738bc.png)

This happens with and without Typescript.

**Comment by davibaltar** [comment]
Hi @ncesar! Thank you for opening the issue.

In this case you must declare: `const endpointsFiles = ['./src/index.js']`. But I'll try to recognize the relative path in this case as well.

**Comment by ncesar** [comment]
Thank you @davibaltar

**Comment by davibaltar** [comment]
The version 2.21.8 has fixed this. If the problem persists, let me know.
