### ISSUE TITLE
Autogenerate body parameters from Joi.

### ISSUE THREAD

**Issue by rbalukja15** [davibaltar/swagger-autogen#16]
I have this schema:

const query = Joi.object().keys({
            userId: Joi.number().required(),
        });

Is there a way to autogenerate the request body from this Joi schema ?

**Comment by davibaltar** [comment]
Hi @rbalukja15.

Thanks for the issue. But unfortunately this type of recognition the lib does not do. Maybe in the future I will be able to implement it, but for now, it's not possible. If I start implementing this in the future, I will open your issue again. 

Thanks
