### ISSUE TITLE
Feature request: Support for export only files

### ISSUE THREAD

**Issue by PhilHannent** [davibaltar/swagger-autogen#163]
My codebase has a router and a handlers sub folder. Each function is its own file. I then have an index file which exports each of the functions:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/813874/183241087-3e06f8c0-1e00-43b6-96d0-ce5b52bc9f60.png">

When entering the inline metadata for a function, it is not picked up when using the export approach. If I use the individual function file directly then it pull in the documentation.

I guess this approach isn't supported, so I'd like to request it.

**Comment by davibaltar** [comment]
Hi @PhilHannent! Thank you for opening the issue. 

Yes, that approach isn't supported, but it is a great feature to integrate with the module! If possible, could you send me just one of the .js files in your handle folder, please? Just to see the structure that you've used in your .js files.

**Comment by PhilHannent** [comment]
Good morning @davibaltar ,

That took slightly longer than I expected to create a minimal example, but it is done:
https://github.com/PhilHannent/example-express-single-file-functions

Whilst the diagnostics route is captured, the documentation in the function is not.

**Comment by davibaltar** [comment]
Hi @PhilHannent! Thank you for the sample project. It'll help me.

I've forked it and I'll try to implement this feature as soon as possible.

**Comment by davibaltar** [comment]
Hi @PhilHannent. The version 2.21.7 has fixed/implemented this. If the problem persists, let me know.

**Comment by PhilHannent** [comment]
Good morning, Thank you! The new version solves the problem for me.

**Comment by Jinbe-im** [comment]
Thanks Bro!
