### ISSUE TITLE
Problem with #swagger.path

### ISSUE THREAD

**Issue by akautsar** [davibaltar/swagger-autogen#169]
Before asking the question, I would like to thank you to @davibaltar for this amazing library. When I'm using this library I have some issue when using path properties

` #swagger.path = '/validate/{id}'`

After executing autogen, I did not find the path ('/validate/{id}') in the generated path. Do I use it incorrectly?

Thank you in advance

**Comment by akautsar** [comment]
My bud, the path must be defined in app.use or router. Thank you for amazing library

**Comment by davibaltar** [comment]
Hi @akautsar! No problem. But any problem, let me know.
