### ISSUE TITLE
swagger.ignore is not working

### ISSUE THREAD

**Issue by hsiangfeng** [davibaltar/swagger-autogen#17]
I try `swagger.ignore` is not working

```
// #swagger.ignore = true
```

or

```
/*
#swagger.ignore = true
*/
```

Is it a problem with my architecture?

because my example is working.

but..if so

controllers/index.js

```
module.exports = {
  home(req, res) {
    // # swagger.ignore = true
    res.render('home', {
      title: 'text',
    });
  },
}
```

routes

```
router
  .get('/', homeController.home)
```

is not working.

But others are normal.

**Comment by davibaltar** [comment]
Hi @hsiangfeng. 

Thank you for the opening the issue. I was able to reproduce your problem here. It is a bug. I'll handle this and submit it in the next version. To workaround the problem for now, you can do:

```
router
  .get('/', homeController.home /* #swagger.ignore = true */ )
```

I hope to resolve it soon.

**Comment by hsiangfeng** [comment]
is working!
Thank @davibaltar  :D

**Comment by davibaltar** [comment]
Greate @hsiangfeng! 

The version 2.5.10 will fix this. Test on your project and tell me if it works. And if you find more bugs, let me know.

Thanks!

**Comment by hsiangfeng** [comment]
thx. 

 version 2.5.10 fixed is workin！
