### ISSUE TITLE
Properties inheritance only works when the router is exported

### ISSUE THREAD

**Issue by juanbomfim22** [davibaltar/swagger-autogen#173]
If you export a function that decorates the app instead of a router, properties won't pass to sub-routes. 

Works:
```js
app.use('/foobar',
/* #swagger.security = [{
  "apiKeyAuth": []
}] */ fooBarRouter)
```

Doesn't work:
```js
module.exports = (app) => {
  app.use(
    '/foobar',
    /* #swagger.security = [{
        "apiKeyAuth": []
    }] */
    router
  );
};
```

Declare the security in the route root middleware, such as:

```js
...
app.use('/v1', routesV1
    /* #swagger.security = [{
        "apiKeyAuth": []
    }] */
...
```

And to manually disable security for a specific endpoint that belongs to '/v1', do the following: 
```js
app.get('/path', (req, res) => {
    ...
    // #swagger.security = null
    ...
})
```

See more about it here: [Properties Inheritance](https://github.com/davibaltar/swagger-autogen#properties-inheritance)

If it doesn't work, let me know, please.

_Originally posted by @davibaltar in https://github.com/davibaltar/swagger-autogen/issues/68#issuecomment-999274482_

**Comment by juanbomfim22** [comment]
As seen in this [example](https://github.com/juanbomfim22/example-swagger-autogen-with-router)

**Comment by davibaltar** [comment]
Hi @juanbomfim22! Thank you for opening the issue.

I'll fix it. Any news, I'll post it here.

**Comment by davibaltar** [comment]
The version 2.22.0 has fixed this. If the problem persists, let me know.
