### ISSUE TITLE
Docs not getting generated.

### ISSUE THREAD

**Issue by uttam-internetsoft** [davibaltar/swagger-autogen#177]
I've created setup for my own flow, but here i'm not able to see my generated docs.
Everything is working fine path is being added but swagger-autogen is not able to pick my comments on route's function handler.

This is what my `route.js` file looks like.

![image](https://user-images.githubusercontent.com/115207461/195010189-d745309a-810f-4dca-a9c6-8025ced3af0f.png)

`AuthController.js` is looking like this

![image](https://user-images.githubusercontent.com/115207461/195010256-fcd383e3-a9c2-42ce-99f4-bfc6f32644f2.png)

other two helper functions 

![image](https://user-images.githubusercontent.com/115207461/195010372-cdf1a79d-10e0-4a16-a260-eb766134aa9e.png)

and 

![image](https://user-images.githubusercontent.com/115207461/195010332-39a8af17-0ccd-441c-a1fb-2d0f53efb255.png)

`swagger.js` file

![image](https://user-images.githubusercontent.com/115207461/195010624-fcfe9bfe-688b-4c1e-9fe8-f063d6d96eef.png)

**Comment by davibaltar** [comment]
Hi @uttam-internetsoft. Thank you for opening the issue. This is a known issue in #79. Because of this, I'll close it and any progress I'll post it there. Thanks!
