### ISSUE TITLE
Use Destructuring assignment 

### ISSUE THREAD

**Issue by hsiangfeng** [davibaltar/swagger-autogen#18]
I use Destructuring assignment

route/users.js

```
const { Users } = UsersController;
router
  .get('/', Users);
```

UsersController.js

```
module.exports = {
  Users() {
    /*
      #swagger.tags = ['購物車相關']
    */
   ....
  }
}
```

tags is not working.

but. The following can wokring

route/users.js

```
router
  .get('/', UsersController.Users);
```

UsersController.js

```
module.exports = {
  Users() {
    /*
      #swagger.tags = ['購物車相關']
    */
   ....
  }
}
```

**Comment by davibaltar** [comment]
Ok @hsiangfeng. I've been implemented some destructuring cases, but it's not 100%. I couldn't reproduce this case of yours here. Can you upload a simple project that reproduces this error? 

This makes it easier to identify the problem.

**Comment by hsiangfeng** [comment]
Ok! @davibaltar is here

https://github.com/hsiangfeng/expressSwagger

You Can look https://github.com/hsiangfeng/expressSwagger/blob/9f5175c16bf25ec213516ce298f6106702b57449/routes/users.js#L9 is wokring!

but https://github.com/hsiangfeng/expressSwagger/blob/9f5175c16bf25ec213516ce298f6106702b57449/routes/users.js#L11 is not wokring.

**Comment by davibaltar** [comment]
Thank you, @hsiangfeng. Unfortunately I've not handled this destructuring case yet. But if you want to use destructuring, the current version recognizes it only when declared directly in the "require" or "import", such as:

``` 
var express = require('express');
var router = express.Router();

const { home, post } = require('../controllers/users');

/* GET users listing. */
router.get('/', home);

router.post('/post', post);

// ...
```  

indirect cases like your project, I will handle it, but it will take a while. So, I'll keep that issue open until I handle it.

**Comment by hsiangfeng** [comment]
oh! Thx.

You're right `const { home, post } = require('../controllers/users');` is working :D

**Comment by davibaltar** [comment]
The version 2.16.0 has fixed this. Thanks!

**Comment by hsiangfeng** [comment]
wow. is working!
very thx @davibaltar !
