### ISSUE TITLE
Endpoint is not generated if express js router name prefix with "request"

### ISSUE THREAD

**Issue by luyendd** [davibaltar/swagger-autogen#182]
I have a route like below
 `export const requestIntervalRouter = express.Router({ mergeParams: true });`
I have run `swagger autogen` but it doesn't work until I renamed my route to `export const reqIntervalRouter = express.Router({ mergeParams: true });`

Here is my example in case you guys need it: https://stackblitz.com/edit/node-2y2yjs?file=src/routes.js

**Comment by davibaltar** [comment]
Hi @luyendd! Thank you for opening the issue and thnks for the sample project!

I'll handle it as soon as possible. Any new I'll post it here.

**Comment by davibaltar** [comment]
The version 2.23.0 has fixed this. If the problem persists, let me know.
