### ISSUE TITLE
Unable to create security definition and use it for jwt validation

### ISSUE THREAD

**Issue by abhishekkarthik1967** [davibaltar/swagger-autogen#19]
// This is my swagger.js doc definition 
securityDefinitions:{
    Authorization:{
      type: "apiKey",
      name: "Authorization",
      description: "Value: Bearer ",
      in: "header",
      scheme: 'bearer'
    }
  }

// This is my output swagger.json and has a empty security

"security": [ ]

// The swagger comment inside my route

  /* #swagger.security = "Authorization": {
      "type": "apiKey",
      "name": "Authorization",
      "description": "Value: Bearer ",
      "in": "header",
      "scheme": "bearer"
    } */
Please provide me a solution at the earliest. As I have to complete a task

**Comment by davibaltar** [comment]
Hi @abhishekkarthik1967. In the comment inside your route:

Instead:
```
/* #swagger.security = "Authorization": {
"type": "apiKey",
"name": "Authorization",
"description": "Value: Bearer ",
"in": "header",
"scheme": "bearer"
} */
```

try it:

```
/* #swagger.security = [{
    "Authorization": []
}] */
```
If it works, let me know.
