### ISSUE TITLE
Incorrect tags and responses documentation

### ISSUE THREAD

**Issue by shoxsz** [davibaltar/swagger-autogen#194]
Hello guys, I found this issues when validating the generated documentation.

The first one is that when you specify an array of tags to the documentation parameter, they will not be converted to objects, and that will fail oas validation, because the validation expect the tags array to be composed of objects.

The second one is when the server tries to auto detect the response and can't find any response on the controllers, it will generate a documentation like this: `responses: {}`, an empty responses object, which will cause oas validations to fail. In my case he can't detect the response type because we use an extra response method(added by us) on the express response object, to facilitate returning specific http method responses, so the module cannot detect my controllers responses, can we fix that to not include any `response` field when there is not detected response?

**Comment by davibaltar** [comment]
Hi @shoxsz. Sorry for the delay. Thank you for opening the issue. 

Good point. For now, there is no a workaround for that. But I'll try to fix this in the next version. Thank you!

**Comment by davibaltar** [comment]
The version 2.23.3 has fixed that, but if the problem persists, let me know. Now, by default, always when a response was empty, the default object will be put on it, for example:

```json
    "responses": {
        "default": {
            "description": ""
        }
    }
```

That way, that validator will be Ok with that.
