### ISSUE TITLE
Swagger autogen is not able to read the router file generated dynamically

### ISSUE THREAD

**Issue by jitendra-sevaro** [davibaltar/swagger-autogen#197]
```
const express = require('express');

const router = express.Router();
const fs = require('fs');
const path = require('path');

function listRoutes(directory, additionalPath = '') {
    fs.readdirSync(directory).forEach((file) => {

        if (file && file.includes('.js')) {
            router.use(`${additionalPath}`, require(`./${additionalPath}/${file}`));
        } else {
            listRoutes(path.join(directory, file), `${additionalPath}/${file}`);
        }
    });
}
listRoutes(__dirname);
module.exports = router;
```
- Things done in code
- read the routes directory recursively
- If a sub directory is found then add that to the path of routes in require and simply import the router, This is to dynamically handle the different versions of the api's

**Comment by davibaltar** [comment]
Hi @jitendra-sevaro. Thank you for opening the issue. 

Swagger-autogen performs just a static analyze of the code. So, unfortunately the lib isn't able to handle dynamic routes. Because of this, I'm closing the issue. But any other thing, let me know.
