### ISSUE TITLE
Skipping routes using TypeScript

### ISSUE THREAD

**Issue by danielmitrov** [davibaltar/swagger-autogen#198]
First of all, this is an awesome package! 🎉

I've noticed some of my routes are missing in the JSON output.
All of the missing routes are typed the following way:
```typescript
app.post<{}, {}, {name: string}>('...', async (req, res) => {
    // ...
});
```
It looks like the parser is skipping this route because of the types following the method.

**Comment by danielmitrov** [comment]
might be related to #175

**Comment by davibaltar** [comment]
Hi @danielmitrov. Sorry for the delay and thank you for opening the issue. 

Exactly, your issue is related with the #175, Because of this, I'm closing this issue and any news about it, I'll post there. Thanks!
