### ISSUE TITLE
Read endpoints from Express Router.

### ISSUE THREAD

**Issue by matheusfenolio** [davibaltar/swagger-autogen#2]
First, congrats! this package is awesome! :smiley:

Now, is there a way to generate the swagger using Router from Express. I was reading the documentation and the examples show the app passing by parameter. It's going to be good if this work with Routes as well.

Here an example:

![image](https://user-images.githubusercontent.com/37229507/97381724-7582a280-18a8-11eb-973c-cbbe6ff1e25e.png)

![image](https://user-images.githubusercontent.com/37229507/97381737-7d424700-18a8-11eb-95d6-66d700c28558.png)

![image](https://user-images.githubusercontent.com/37229507/97381833-ad89e580-18a8-11eb-9b5a-57e3f85fbf29.png)

**Comment by davibaltar** [comment]
Oi Matheus. Como somos conterrâneos, acredito que podemos falar em pt-br. Obrigado pelo comentário! Sobre as rotas, já tenho isso no meu "to do list" aqui.. é uma necessidade urgente msm! Porém vai exigir um tempo de mão de obra pra eu implementar. Por enquanto, eu não tenho prazo, mas espero conseguir fazer até o final desse ano ou início do ano que vêm. Espero eu! Mas caso vc tenha mais algum outro ponto, ou sugestão de melhora, pode falar, é sempre bem vindo!

Att.

**Comment by RafaelAugustoS** [comment]
Eu ia abrir uma issue sobre isso agora, mas vejo que já está no todo. Thanks

**Comment by davibaltar** [comment]
**en-US:** The version 2.x focused on solving this issue. If you have problems, open an issue.

**bt-BR:** A versão 2.x teve como foco a resolução desse problema. Caso tenha outros problemas, abra uma issue. Att
