### ISSUE TITLE
Incorrect example definition of array 

### ISSUE THREAD

**Issue by nettawang** [davibaltar/swagger-autogen#20]
I was looking at creating an example: 

/* #swagger.parameters['quiz'] = {
        in: 'body',
        type: "object",
        schema: {
            "quiz_id": 1,
            "questions": [0, 1, 2],
            "quiz_name": "State COVID Line Up",
            "quiz_instructions": "Do the thing" 
        }
    } */

But the array for "questions" shows up as [0]. Alternatively, when I make an array of strings instead of integers, it shows up as [string]. How do I get the actual numbers and strings values to show up instead? I found this similarly happens in this [documentation](https://www.npmjs.com/package/swagger-autogen#schema-and-definitions) for myArrayofNumbers and myArrayofStrings

<img width="564" alt="Screen Shot 2021-02-09 at 9 26 18 PM" src="https://user-images.githubusercontent.com/29472503/107468779-7cfb4e00-6b1d-11eb-9b3c-59bfa2cdcd1c.png">

**Comment by davibaltar** [comment]
Hi @nettawang. Thank you for opening the issue. 

This is really a bug. I'll handle it and submit in the next version.

**Comment by davibaltar** [comment]
The version 2.5.11 fixed it. If the problem persists, let me know.
