### ISSUE TITLE
Endpoint parameters are not being detected when controller functions are separated in multiple CommonJS files

### ISSUE THREAD

**Issue by hgcordeiro** [davibaltar/swagger-autogen#200]
I have the following structure (I'm using the https://github.com/davibaltar/example-swagger-autogen-with-router code and just did the changes I needed to reproduce the issue):
- src/
  - index.js
  - routes.js
  - controllers/
      - users/
         - index.js
      - users2/
         - add.js
         - get.js
         - index.js
 - swagger.js
 
 This is my `swagger.js` file:
 ```js
 const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./src/index.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./src/index')           // Your project's root file
});

 ```

In `src/router.js` I'm importing the controllers  for the post and get routes (yes, I have two directories for the users controller for a reason that I'll explain later on, bear with me).
```js
const express = require('express')

// const usersController = require('./controllers/users')
const usersController = require('./controllers/users2')

const router = express.Router()

router.post('/users', usersController.add)
router.get('/users/:id', usersController.get)

module.exports = router
```

The controller has a index file and each function is in its own file:
`src/controllers/users2/index.js`
```js
module.exports = {
  add: require('./add'),
  get: require('./get'),
};
```

`src/controllers/users2/add.js`
```js
module.exports = async (req, res, next) => {
  const user = req.body.user;
  res.status(201).json({
      data: user,
      message: 'Authentication successed'
  })
};
```

`src/controllers/users2/get.js`
```js
module.exports = async (req, res, next) => {
  const users = []
  const data = users.find(e => e.id === req.params.id)

  res.status(200).json({
    data: [],
    message: 'Successfully found'
  })
};
```

If I run the autogen, the body parameter for the post is not detected, as if it couldn't reach the `src/controllers/users2add.js` file for some reason.
If I add the functions `add` and `get` directly to the  controller index file (what I am doing in `src/controllers/users/index.js` as shown below, and that's why I have two different `user` directories), the body parameter is detected and added to the swagger file.
`src/controllers/users/index.js`
```js
module.exports = {
  add: async (req, res, next) => {
    const user = req.body.user;

    res.status(201).json({
        data: user,
        message: 'Authentication successed'
    })
  },
  get: async (req, res, next) => {
    const users = []
    const data = users.find(e => e.id === req.params.id)

    res.status(200).json({
        data: [],
        message: 'Successfully found'
    })
	},
};
```

UPDATE: after further investigation, I believe this issue is related to importing modules using `require`.
If I rewrite files in folder `src/controllers/users2` as ES Modules, the parameters are detected and added to the output file:
`src/controllers/users2/index.js`
```js
import * as add from './add';
import * as get from './get';

export {
  add,
  get
};
```

`src/controllers/users2/add.js`
```js
export default add = async (req, res, next) => {
  const user = req.body.user;
  if(user) {
    res.status(201).json({
        data: user,
        message: 'Authentication successed'
    })
  } else {
    res.status(500).json({
      message: 'Error'
    })
  }
};
```

`src/controllers/users2/get.js`
```js
export default get = async (req, res, next) => {
  const users = []
  const data = users.find(e => e.id === req.params.id)

  res.status(200).json({
    data: [],
    message: 'Successfully found'
  })
};
```

**Comment by davibaltar** [comment]
Hi @hgcordeiro. Sorry for the delay and thank you for opening the issue with a sample code!

Unfortunately the lib is not prepared to for this kind of pattern (CommonJS):
```
module.exports = {
  add: require('./add'),
  get: require('./get'),
};
```

I had not thought about this case when I made the implementations for CommonJS. I'll try to implement it as soon as possible. Any news, I'll post it here. Thanks!

**Comment by davibaltar** [comment]
The version 2.23.3 has fixed that, but if the problem persists, let me know.

**Comment by hgcordeiro** [comment]
Hello @davibaltar.
Thanks for your response and for fixing the issue!
