### ISSUE TITLE
"out of structure" error when using oneOf

### ISSUE THREAD

**Issue by denis-haskin-elemental** [davibaltar/swagger-autogen#202]
swagger-autogen version 2.23.1

We have had working OpenAPI generation.  We changed to use `oneOf` in one of our endpoints and running swagger-autogen now results in this error

```
[swagger-autogen]: '#swagger.requestBody' out of structure in
'/Users/denis/em/vh/resource-domain/equipment-model-edge-service/src/systems/ExpressSystem/routes/api/v1/index.ts' ... router.post('/equipment-models', ...)
```

and the resulting openapi.json is invalid.

The function and its swagger doc:

```
const add = async (req: Request, res: Response) => {
  /**
    #swagger.description = 'Create a equipment model'
    #swagger.tags = ['Equipment Models']
    #swagger.requestBody = {
      required: true,
      content: {
        "application/json": {
          schema: { 
            oneOf: [
              {
                $ref: "#/components/schemas/EquipmentModelAddRequestGeneric" },
              },
              {
                $ref: "#/components/schemas/EquipmentModelAddRequestNotGeneric" },
              }
            ]
          }
        }
      }
    }
...etc...
  */
```

The 2 schemas referenced are getting generated in the openapi.json just fine, so I don't think there's a problem with them.

Suggestions?  According to other issues I've seen filed (and the documentation) this *should* be working.

**Comment by davibaltar** [comment]
Hi @denis-haskin-elemental. No problem. I'm always trying to improve log erros. But I'm happy to know you found the solution.
