### ISSUE TITLE
How to automatically detect Models using Sequelize

### ISSUE THREAD

**Issue by juanbomfim22** [davibaltar/swagger-autogen#205]
Hey! I'm using swagger-autogen for months and it's been running flawlessly. 

I am in the process of refactoring some routes' documentation and I noticed that I can use the `$ref` attribute under `definitions` to reuse the same schema across files. However, I'm using Sequelize as an ORM and I cannot see how its models can be detected automatically using swagger-autogen. 

How can I achieve that?

**Comment by juanbomfim22** [comment]
One way to generate the Models objects automatically is to use a script. 

I found out that [sequelize-swagger](https://github.com/kissarat/sequelize-swagger) does that and I just had to download and insert it into my project (because it's not available on npm). With the use of `describeModel`, it was possible to generate the `definitions` of each model from the database `connection` file and export it:

```js
// database/index.js
const connection = new Sequelize(dbConfig);

const modelsObject = Object.fromEntries(
  Object.entries(connection.models).map(([key, value]) => [
    key,
    describeModel(value),
  ])
);

module.exports = {
  connection,
  modelsObject,
};
```
Then I used it in the `doc` configuration:

``` js
// swagger.js
const { modelsObject } = require('../database/index');

const doc = {
   //...
  definitions: modelsObject,
};
```

**Comment by davibaltar** [comment]
Hi @juanbomfim22. Thank you for this information.
