### ISSUE TITLE
Inappropriate output with JSON Schema Keywords in OpenAPI 3.0

### ISSUE THREAD

**Issue by juanbomfim22** [davibaltar/swagger-autogen#206]
Given the [keywords](https://swagger.io/docs/specification/data-models/keywords/) using OpenAPI 3.0 (w/ `openapi: '3.0.0'`):

``` js
const doc = {
  // ...
  definitions: {
    Projeto: {
      type: 'object',
      required: ['id', 'createdAt', 'updatedAt'],
      properties: {
        id: { type: 'number', format: 'int32' }, 
        //...
      },
    },
  },
};
```

In this example, the output generated expands objects recursively, with the `type`-`property` pattern, even when they're expressed properly as a valid JSON with the expected specification keys.

![image](https://github.com/davibaltar/swagger-autogen/assets/55420785/1cbb94bb-2163-446e-9791-2a9da645ef51)

We can see that it's created an unexpected nested structure of objects with `type`, `property`, and `example` keys, which reflects in the final Swagger page. 

The expected output should be the same as specified in the `doc` section:

![image](https://github.com/davibaltar/swagger-autogen/assets/55420785/2cb01da5-4cc3-4fca-aa23-c4f254cf6138)

**Comment by davibaltar** [comment]
Hi @juanbomfim22. Sorry for the delay and thank you for opening the issue.

For this case, you case use the '@definitions'. With that, the lib won't render the definitions. You can see more about it [here](https://github.com/davibaltar/swagger-autogen#schema-and-definitions).

In your case:

```js
const doc = {
  // ...
  '@definitions': {
    Projeto: {
      type: 'object',
      required: ['id', 'createdAt', 'updatedAt'],
      properties: {
        id: { type: 'number', format: 'int32' }, 
        //...
      },
    },
  },
};
```

If it doesn't work, let me know and I'll reopen this issue.
