### ISSUE TITLE
Controller Naming Issue

### ISSUE THREAD

**Issue by anujkumar14** [davibaltar/swagger-autogen#22]
[https://github.com/davibaltar/example-swagger-autogen-with-router]

In the above example, if i change the name of ToolsController to VarController, all the documentation from swagger is gone.

**Comment by davibaltar** [comment]
Hi @anujkumar14. Thank you for opening the issue. 

I tried to reproduce the problem, but I couldn't. Could you submit a copy of 'example-swagger-autogen-with-router' in your repository that reproduces the problem and sends me the link? This makes it easier to identify the problem.

**Comment by anujkumar14** [comment]
I have added below code in show function of VarController(which was initially ToolsController)
 /* 	#swagger.tags = ['User']
            #swagger.description = 'Endpoint to sign in a specific user' */

Ideally it should add documentation for '/test-get' endpoint. It works fine if i don't change the name of ToolsController.
https://github.com/anujkumar14/example-swagger-autogen-with-router

I think there is some conflict with javascript default keywords.

**Comment by davibaltar** [comment]
Ok @anujkumar14. Thank you. I'll handle it and submit in the next version as soon as possible.

**Comment by davibaltar** [comment]
The version 2.6.3 fixed it. If the problem persists for you, let me know.
