### ISSUE TITLE
Tsconfig parse fails at trailing commas

### ISSUE THREAD

**Issue by TheTimeWalker** [davibaltar/swagger-autogen#28]
With a newer version of Typescript, it's now possible that you can have trailing commas inside a { ... } object just like in js/ts files. However, this means that it now breaks JSON.parse(tsconfig) if it's being read. With a config similar like this:

```
{
  "extends": "@tsconfig/node14/tsconfig.json",
  "compilerOptions": {
    "outDir": "./dist",
    "moduleResolution": "node",
  },
  "include": ["./src/**/*"]
}
```

the exception is this:

```
UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token } in JSON at position 121
    at JSON.parse (<anonymous>)
    at {location}/node_modules/swagger-autogen/src/handle-files.js:1089:33
```

When the comma after moduleResolution is removed, swagger-autogen works fine.

**Comment by davibaltar** [comment]
Hi @TheTimeWalker. Thank you for opening the issue. 

I didn't know about this in the newer version of Typescript. Thanks for this information. 

I'll handle this as soon as possible.

**Comment by davibaltar** [comment]
The version 2.6.9 fixed this. If the problem persists, let me know.
