### ISSUE TITLE
exporting using index file removes documentation

### ISSUE THREAD

**Issue by anujkumar14** [davibaltar/swagger-autogen#29]
I have created a admin-controller and added show method. 
If i use Index.js file  to export the function, documentation goes away.

Reference route: 'router.get('/test-get', AdminController.show)'

https://github.com/anujkumar14/example-swagger-autogen-with-router

**Comment by davibaltar** [comment]
Hi @anujkumar14. Thank you for opening the issue. 

I'll verify this case and try to handle as soon as possible.

**Comment by davibaltar** [comment]
The version 2.7.1 fixed this. If the problem persists, let me know.
