### ISSUE TITLE
Module works with typescript?

### ISSUE THREAD

**Issue by antoniorrm** [davibaltar/swagger-autogen#3]
Parabéns pela iniciativa e projeto, estava atrás e encontrei ele. Gostaria de saber se ele funciona em um api com typescript ou so com js msm.

**Comment by davibaltar** [comment]
Olá Antonio. Obrigado e desculpa pela demora em responder, mas sobre funcionar com ts, eu nunca testei, mas caso vc tenha testado, me fala, senão, vou manter essa issue em aberto uns dias pra ver se alguem que ja testou se manifesta. att

**Comment by antoniorrm** [comment]
Ta bom, vou tentar testar também.

**Comment by davibaltar** [comment]
Implementei algumas features para reconhecer TypeScript. Ainda não está 100% mas já funcionou para alguns projetos aqui. A versão 2.x vai ter isso como foco. Espero subir mais features em breve. Att

**Comment by eden-lane** [comment]
It generates empty swagger-output.json for me. It has **all** my methods but no descriptions and other stuff.
