### ISSUE TITLE
Nested routes path not generated correctly

### ISSUE THREAD

**Issue by ashwini-desai** [davibaltar/swagger-autogen#32]
The spec paths are generated correctly when the routes or endpoints are directly listed as:
```
    import users from './users';

    app.get('/users', users);
```
If `app.js` is structured in nested way, where all routes aren't listed at top level, like eg:
```
   app.js
       import { Router } from 'express';
       import users from './users';
       import healthCheck from './healthCheck';

      const router = Router();
      router.get('/healthCheck', healthCheck);
      router.use('/users', users);
  
  users.js
     import { Router } from 'express';
     import { getApps } from './getApps';

      const router = Router();
      router.get('/:userId/apps', getApps);
```

We are facing following issues:
1. If our `swagger.js` includes only `app.js`, generated spec json only includes `/healthCheck` route.
2. If in `swagger.js` includes all files above, i.e `app.js` and `users.js`, the generated path in this case looks like -
`/:userId/apps`. It does not include `/users` prefix

We checked this[https://github.com/davibaltar/example-swagger-autogen-with-router] example repository, but even with same code configuration, it isn't working for us.

**Comment by davibaltar** [comment]
Hi @ashwini-desai. Thank you for opening the issue. 

I'm trying to reproduce this problem here, but I'm can not. Could you submit a simple project in your repository that reproduces just this problems and send me the link? 

That way it is easier to identify the problem.

**Comment by ashwini-desai** [comment]
Thanks for the quick response @davibaltar.

[Here](https://github.com/ashwini-desai/express-swagger-autogen) is the link to sample repository.
You can observe `./docs/api-spec.json` file after two commits:
1. [commit](https://github.com/ashwini-desai/express-swagger-autogen/commit/8c8cfcf7cdfb39b09e96f10eab5291e31a3bed9f) : Where only one file is added to `swagger.js` since I am using express router.
2. [commit](https://github.com/ashwini-desai/express-swagger-autogen/commit/844ced74c4bf065fbb5237a361b4fe530a04dcb8) : Where I have added all `index.js` files to `swagger.js`.

**Comment by davibaltar** [comment]
@ashwini-desai, in your swagger.js:

Instead of:
```
const endpointsFiles = ['./dist/routes/index.js', './dist/routes/v1/index.js', './dist/routes/v2/index.js'];
```

Change to:
```
const endpointsFiles = ['./src/app.ts'];
```

Note: pass the **src** instead of **dist**.

Try this and tell me if it doesn't work.

**Comment by ashwini-desai** [comment]
@davibaltar 

Changing to `const endpointsFiles = ['./src/app.ts'] ` generates the file correctly, but throws this warning:

```
(node:1838) UnhandledPromiseRejectionWarning: /Users/ashwinia.mutalikdesai/Projects/medly/core/express-swagger-autogen/src/app.ts:1
import bodyParser from 'body-parser';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by ashwini-desai** [comment]
@davibaltar We are facing one more issue. tags, operationId, description etc are getting added to some routes and not for some others. See this [commit](https://github.com/ashwini-desai/express-swagger-autogen/commit/2f3817afa53524d2b67dcc2d6aa071b8b4e70edd) and the generated [spec file](https://github.com/ashwini-desai/express-swagger-autogen/blob/master/docs/api-spec.json)

Let me know if I should create a new ticket for this.

**Comment by eduardo-fernandes-marques** [comment]
Hello @davibaltar, I'm trying to use this lib to generate my contracts.

I have a structure like this:

routes: 
![image](https://user-images.githubusercontent.com/47123758/111553699-aeda8280-8763-11eb-882b-83784871e227.png)

route example: 
![image](https://user-images.githubusercontent.com/47123758/111553762-c6197000-8763-11eb-85ac-8e29ac2c90df.png)

In `app.ts` I'm using like this:

  `app.use(router);`

My swagger config file is like this:

`const swaggerAutogen = require("swagger-autogen")();

import { config } from "#/config/constants";
import fixtures from "#/config/server/fixtures.json";

const doc = {
  info: {
    version: "1.0.0",
    title: "Credit Pricing BO BFF",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: `localhost:${config.serverPort}`,
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "Organization",
      description: "Endpoints",
    },
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: "apiKey",
      in: "header",
      name: "X-API-KEY",
      description: "any description...",
    },
  },
  definitions: {
    Entity: {
      ...fixtures.service.organization.entity,
    },
  },
};

const outputFile = "./swagger_output.json";
const endpointsFiles = [
  config.script === "swagger"
    ? "dist/src/routes/index.js"
    : "src/routes/index.ts",
];

(async () => {
  await swaggerAutogen(outputFile, endpointsFiles, doc);
})();
`

And than i import like this in my `index.ts`:
`import "#/config/swagger";`

So when I run my script of development `npm run dev` it should generate the contracts but it's not working. It generates the spec file but it's not recognizing the paths of the routes. I'm getting this json: 

`{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Credit Pricing BO BFF",
    "description": "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  "host": "localhost:8080",
  "basePath": "/",
  "tags": [
    {
      "name": "Organization",
      "description": "Endpoints"
    }
  ],
  "schemes": [
    "http",
    "https"
  ],
  "securityDefinitions": {
    "apiKeyAuth": {
      "type": "apiKey",
      "in": "header",
      "name": "X-API-KEY",
      "description": "any description..."
    }
  },
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {},
  "definitions": {
    "Entity": {
      "type": "object",
      "properties": {
        "idEntidade": {
          "type": "string",
          "example": "010108"
        },
        "codigoEntidade": {
          "type": "string",
          "example": "0101"
        },
        "tipoEntidade": {
          "type": "string",
          "example": "AGENCIA"
        },
        "entidadePaiId": {
          "type": "string",
          "example": "010101"
        },
        "entidadesFilhas": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "idEntidade": {
                "type": "string",
                "example": "01010812"
              },
              "nomeFantasia": {
                "type": "string",
                "example": "Point"
              }
            }
          }
        }
      }
    }
  }
}`

I already have tried many things to fix it but i can't find out what is my mistake. Can you give me a hand?

I already want to thank you for your time and congratulate you for this lib.

**Comment by davibaltar** [comment]
Hi @eduardo-fernandes-marques. Thank you for opening the issue.

I will open a new issue for your case, because when I submit the correction and refenciate this issue, this issue will be closed automatically. 

Let's check your case on issue #34.

**Comment by davibaltar** [comment]
And @ashwini-desai,

About the error "(node:1838) UnhandledPromiseRejectionWarning ..." this is because of TypeScript. The ways to get around this would be to do as you did:

**swagger.js**  
```
swaggerAutogen(outputFile, endpointsFiles);
```

and generate the documentation with: `npm run swagger-autogen`

**package.json**  
```
"scripts": {
    ...
    "swagger-autogen": "node swagger.js"
}
```

another way, maybe you could do:

**swagger.js**  
```
swaggerAutogen(outputFile, endpointsFiles).then( () => {
    require("./dist/server.js")
})
```

I could only think of these two ways, but if I find any other solution, I'll post it here.

And about the '/healthCheck' not recognizing tags, operationId, description etc, I identified that it's a bug in the lib. I will handle this as soon as possible and I'll let you know when it's fixed. Thanks for bring up this case.

**Comment by davibaltar** [comment]
And @ashwini-desai,

About the error "(node:1838) UnhandledPromiseRejectionWarning ..." this is because of TypeScript. The ways to get around this would be to do as you did:

**swagger.js**  
```
swaggerAutogen(outputFile, endpointsFiles);
```

and generate the documentation with: `npm run swagger-autogen`

**package.json**  
```
"scripts": {
    ...
    "swagger-autogen": "node swagger.js"
}
```

another way, maybe you could do:

**swagger.js**  
```
swaggerAutogen(outputFile, endpointsFiles).then( () => {
    require("./dist/server.js")
})
```

I could only think of these two ways, but if I find any other solution, I'll post it here.

And about the '/healthCheck' not recognizing tags, operationId, description etc, I identified that it's a bug in the lib. I will handle this as soon as possible and I'll let you know when it's fixed. Thanks for bring up this case.

**Comment by ashwini-desai** [comment]
Thanks @davibaltar !

**Comment by davibaltar** [comment]
The version 2.7.3 has fixed this. There are others TypeScript's features to implement, but I'm already checking it.
