### ISSUE TITLE
Not recognizing the paths of the routes (TypeScript )

### ISSUE THREAD

**Issue by davibaltar** [davibaltar/swagger-autogen#35]
Author: @eduardo-fernandes-marques

**Content:**

Hello @davibaltar, I'm trying to use this lib to generate my contracts.

I have a structure like this:

routes: 
![image](https://user-images.githubusercontent.com/47123758/111553699-aeda8280-8763-11eb-882b-83784871e227.png)

route example: 
![image](https://user-images.githubusercontent.com/47123758/111553762-c6197000-8763-11eb-85ac-8e29ac2c90df.png)

In `app.ts` I'm using like this:

  `app.use(router);`

My swagger config file is like this:

```const swaggerAutogen = require("swagger-autogen")();

import { config } from "#/config/constants";
import fixtures from "#/config/server/fixtures.json";

const doc = {
  info: {
    version: "1.0.0",
    title: "Credit Pricing BO BFF",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: `localhost:${config.serverPort}`,
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "Organization",
      description: "Endpoints",
    },
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: "apiKey",
      in: "header",
      name: "X-API-KEY",
      description: "any description...",
    },
  },
  definitions: {
    Entity: {
      ...fixtures.service.organization.entity,
    },
  },
};

const outputFile = "./swagger_output.json";
const endpointsFiles = [
  config.script === "swagger"
    ? "dist/src/routes/index.js"
    : "src/routes/index.ts",
];

(async () => {
  await swaggerAutogen(outputFile, endpointsFiles, doc);
})();
```

And than i import like this in my `index.ts`:
`import "#/config/swagger";`

So when I run my script of development `npm run dev` it should generate the contracts but it's not working. It generates the spec file but it's not recognizing the paths of the routes. I'm getting this json: 

`{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Credit Pricing BO BFF",
    "description": "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  "host": "localhost:8080",
  "basePath": "/",
  "tags": [
    {
      "name": "Organization",
      "description": "Endpoints"
    }
  ],
  "schemes": [
    "http",
    "https"
  ],
  "securityDefinitions": {
    "apiKeyAuth": {
      "type": "apiKey",
      "in": "header",
      "name": "X-API-KEY",
      "description": "any description..."
    }
  },
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {},
  "definitions": {
    "Entity": {
      "type": "object",
      "properties": {
        "idEntidade": {
          "type": "string",
          "example": "010108"
        },
        "codigoEntidade": {
          "type": "string",
          "example": "0101"
        },
        "tipoEntidade": {
          "type": "string",
          "example": "AGENCIA"
        },
        "entidadePaiId": {
          "type": "string",
          "example": "010101"
        },
        "entidadesFilhas": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "idEntidade": {
                "type": "string",
                "example": "01010812"
              },
              "nomeFantasia": {
                "type": "string",
                "example": "Point"
              }
            }
          }
        }
      }
    }
  }
}`

Maybe you are asking yourself why i have a condition for my endpoints in my config file that's just a way to run the config when is running in the environment or if i run the swagger script `npm run swagger`, that does something like this `npm run build && node node dist/src/config/swagger.js`.

I already have tried many things to fix it but i can't find out what is my mistake. Can you give me a hand?

I already want to thank you for your time and congratulate you for this lib.

_Originally posted by @eduardo-fernandes-marques in https://github.com/davibaltar/swagger-autogen/issues/32#issuecomment-801521345_

**Comment by davibaltar** [comment]
Hi @eduardo-fernandes-marques. Thank you for the issue.

Could you submit a simple project in your repository that reproduces just this problems and send me the link? It can contain a single endpoint.

That way it is easier to identify the problem.

**Comment by eduardo-fernandes-marques** [comment]
Hi @davibaltar.

Here is the repository that you asked for:

https://github.com/eduardo-fernandes-marques/swagger-generator

Any doubt you can ask for me here.

**Comment by davibaltar** [comment]
Hi @eduardo-fernandes-marques.

About its issue, today I checked the possibility to fix it. The module is still in progress and your case depends on other implementations that haven't yet been made, such as:

1. Recognize template string, for example: `/${config.apiPath}/${config.apiVersion}/${path || ""}`
2. Recognize referenced variables, for example: "organizationRouter.path" in "router.use(organizationRouter.path, organizationRouter.router);"
3. Recognize alias in the imports, for example: "import * as organizationRouter from "./organization.router"

All of these features take time to implement. For now, the module it not be able to serve your project. But I will add this features in my "todo" list. I'll keep this issue open for the future use and I have also made a copy of your project in my computer (if you wish to delete it, be all right).

Thanks for now and if future versions implement these features above, I'll comment and close this issue.

**Comment by eduardo-fernandes-marques** [comment]
Thanks a lot for your return @davibaltar. I tried to find out what was the error with my project but i didn't undestand to much the lib. I would like to give a hand.

**Comment by NikolaLukic1** [comment]
Is this issue related to not recognising the same paths on router?

Example:
I have router.post(/item) and router.put(item).

Result in swagger_output file is always the last file in endpoints array. 
``router.post(
    '/nutrition/meal',
    validate({body: dailyMealSchema}),
    /*
    #swagger.description = 'Add meal daily nutrition endpoint' 
    #swagger.tags = ['DailyNutrition']

    #swagger.parameters['body'] = {
            in: 'body',
            description: 'add daily meal body',
            required: true,
            schema: { $ref: "#/definitions/AddDailyMeal" }
    } 

    #swagger.responses[200] = { 
    schema: { "$ref": "#/definitions/AddDailyMealResponse" },
    description: "Add daily meal response" } */
    controller.AddMeal
)``

``router.delete(
    '/nutrition/meal',
    deleteMealSchema,
    /*
    #swagger.description = 'Delete meal endpoint' 
    #swagger.tags = ['DailyNutrition']
    #swagger.parameters['id'] = { description: 'Daily nutrition id' }
    #swagger.parameters['mealGuid'] = { description: 'Meal guid' }

    #swagger.responses[200] = { 
    schema: { "$ref": "#/definitions/DeleteMealResponse" },
    description: "Delete meal response" } */
    controller.DeleteMeal
)
``

**Comment by davibaltar** [comment]
Hi @NikolaLukic1. I believe your problem is different. Anyway, I'll transfer your case to a new issue to handle it.

**Comment by LenhardErwan** [comment]
Hey, great job on this module. I think I got the same problem.

I have a file that looks like this
```js
class API {
	constructor() {
		this.router = express.Router();

		this.router.use('/users', new UserMW().router);
		this.router.use('/images', new ImageMW().router);
		this.router.use('/docs', swaggerUI.serve);
		this.router.get('/docs', swaggerUI.setup(swaggerDocument.default));
	}
}
```

And for example, the ImageMW you see above look like this 

```js
class ImageMW {
	constructor() {
		this.router = express.Router();
		this.router.get('/subjects/', [this.getAllSubjects]);
		this.router.get('/tags/', [this.getAllTags]);
		this.router.get('/ressources/', [this.getRandomRessource]);
		this.router.get('/ressources/:id', [this.getRessource]);
...
```

Currently, if I link the module to the API file, nothing happens. However, if I make it link to the MW it works, well it generates paths for me anyway.
So maybe I'm doing it wrong too, and that's possible. But from what I understand, it's on your TODO list, right?

**Comment by davibaltar** [comment]
Hi @LenhardErwan! Thanks for reporting this. 

Currently the lib doesn't recognize this pattern with `new someThing().router`. But I'll add it in my TODO list. Could you submit a sample project with this and send me the link? That way is easier to identify and handle the pattern. Thanks for now.

**Comment by davibaltar** [comment]
The version 2.18.6 has fixed somethings about this. If the problema persists, let me know.
