### ISSUE TITLE
Is there anyway to add enum values in schema definitions? 

### ISSUE THREAD

**Issue by DhanyashreeNarayani** [davibaltar/swagger-autogen#36]
It would be great to be able to add enum values in the schema definitions using the example definition.

**Comment by davibaltar** [comment]
Hi @DhanyashreeNarayani. Thank you for opening the issue.

Thanks for the suggestion. I will mark your issue as a feature and try to implement it as soon as possible. If you have some examples using enum, post here, please.

**Comment by thanhnguyennguyen** [comment]
keeping my eyes on this

**Comment by davibaltar** [comment]
The version 2.14.0 has implemented this feature. Se about it [here](https://www.npmjs.com/package/swagger-autogen#enums).

**Comment by davibaltar** [comment]
The version 2.15.0 has fixed a bug about Enums.
