### ISSUE TITLE
Feature Request: Generate spec file in openapi 3.0.0

### ISSUE THREAD

**Issue by ashwini-desai** [davibaltar/swagger-autogen#37]
Currently this library generates spec in `swagger 2.0` format which is old and doesn't support a few functionalities.
It will be great to have specs generated in `openapi 3.0.0`.

**Comment by ashwini-desai** [comment]
@davibaltar : Most of our applications are already on v3 and hence maintaining one of them using older versions is difficult. This is also because we are using `authentication` or `securityDefinitions`  are needed. Open api 3 has `openid connect` mechanism which `swagger 2.0` doesn't have. We are using this feature. Also, the way of defining these, schemas etc is different in `openapi 3.0`. Hence the spec file generated won't be forward compatible for us if we stick to `swagger 2.0`. Hope this helps.

**Comment by ashwini-desai** [comment]
@davibaltar Appreciate your efforts!

**Comment by wang-chi** [comment]
Hi @davibaltar Thanks for your efforts, when implementing swagger into the project, I also found the `examples` on the `openapi 3` is not working, and I modified some parts to work the package.
Like this
1. Add `examples` into TEMPLATE
on `statics.js`
```js
const TEMPLATE = {
    ...
    definitions: {},
    examples: {}  // This Line
};
```
2. Implementing
on `swagger.js`
```js
const doc = {
    ...
    definitions: {},
    examples: {
        Users:{
            value:{
                name: 'Jhon Doe',
                age: 29
            },
            summary: "Sample for User"
        }
    }
}
```

`EndPoint file`

```js
    app.post('/users', (req, res) => {
        ...
        /* #swagger.requestBody = {
              required: true,
              content: {
                "application/json": {
                    schema: { $ref: "#/definitions/Users" },
                    examples: { $ref: "#/examples/Users" }
                  }
              }
            }
        */
        ...
    })
```

Hope this features can insert to next version~~

**Comment by wang-chi** [comment]
@davibaltar Okay, Appreciate the next version

**Comment by davibaltar** [comment]
The version 2.14.0 has implemented this feature.
