### ISSUE TITLE
Parameter Attributes

### ISSUE THREAD

**Issue by mattknappchhj** [davibaltar/swagger-autogen#38]
Is it possible to add minLength and maxLength attributes to a body parameter? When I try to force the proper JSON like the below, it simply assumes that everything within schema is actually part of the object:

`/* #swagger.parameters['obj'] = {
		in: 'body',
		schema: {
			required: ['name'],
			properties: {
				"name": {
					"type": "string",
	                "minLength": 2,
	                "maxLength": 250,
	                "example": "Blah Blah"
				}
			}
		}
	} */`

**Comment by davibaltar** [comment]
Hi @mattknappchhj. Thank you for opening the issue.

Thanks for the suggestion. I will mark your issue as a feature and I will check the possibility of implementing this.

**Comment by davibaltar** [comment]
The version 2.16.0 has implemented the property `'@schema'` that won't process the schema. See more about it [here](https://www.npmjs.com/package/swagger-autogen#schema)

**For example:** 
```js
    app.get('/path', (req, res) => {
        ...
         /* #swagger.parameters['obj'] = { 
            in: 'body', 
            '@schema': { 
                "required": ["name"], 
                "properties": { 
                    "name": { 
                        "type": "string", 
                        "minLength": 2, 
                        "maxLength": 250, 
                        "example": "Blah Blah" 
                    } 
                } 
            } 
        } */
        ...
    })
```
