### ISSUE TITLE
Express middleware that takes in object as input variable breaks automatic parameter detection

### ISSUE THREAD

**Issue by aiavci** [davibaltar/swagger-autogen#39]
### Description
Using a middleware that has an object input field in a route breaks the auto-detection of the body parameter in the route. I tried removing this input field and saw that the body parameter was detected.

### Example code
```
// Middleware definition in its own file. e.g. middlewares/middleware.js
module.exports.doSomething = ({propertyOne, propertyTwo}) => {
  return (req, res, next) => {
    next()
  }
}

// Called from route in another file. e.g. routes/index.js
router.post(
  "/",
  doSomething({ propertyOne: "abc", propertyTwo: "abc" }), 
  (req, res, next) => {
    // THIS IS NOT DETECTED AUTOMATICALLY
    const sampleBodyParam = req.body.sampleBodyParam;

    res.send()
  }
)
```

**Comment by davibaltar** [comment]
Hi @aiavci. Thank you for opening the issue. 

I'll check this and handle as soon as possible.

**Comment by davibaltar** [comment]
The version 2.7.6 has fixed this. But if the problem persists, let me know.
