### ISSUE TITLE
Erro utilizando arquivo de controller

### ISSUE THREAD

**Issue by EzequielHaccourt** [davibaltar/swagger-autogen#4]
Desculpe estar escrevendo em português, acho que vou conseguir me expressar melhor.

Estou tentando utilizar o pacote da seguinte maneira:

`const Jwt = require('../middlewares/Jwt')
const Log = require('../middlewares/LOG')
const PMCMControler = require('../controllers/PMCMControler')
module.exports = (app) => {

    app.get('/PM-CM',[Jwt,Log],PMCMControler.viewAll)
}`

Quando utilizo um array de middlewares na minha rota e um controller para processamento o autogen da crash na função getQueryIndirectly

`if (req && elem.split(new RegExp(" .*?\\s*=\\s*" + req + "\\.query(\\s|\\n|;)", "gm").length > 1)) {
                          ^

SyntaxError: Invalid regular expression: / .*?\s*=\s*[Jwt\.query(\s|\n|;)/: Unterminated character class`

Se utilizar somente 1 middleware no array funciona normalmente 
` app.get('/PM-CM',[Jwt],PMCMControler.viewAll)   //OK`

Se utilizar mais de 1 middleware e não usar um controller também funciona
` app.get('/PM-CM',[Jwt,Log],(req,res) =>{})  // OK`

Existe alguma limitação quanto ao uso do array de middlewares na rota?

**Comment by davibaltar** [comment]
Olá, Ezequiel. Na verdade o módulo ainda não faz o tratamento de rotas. Inclusive comecei a implementar essa feature semana passada, mas ainda estou trabalhando nela. Mas eu consegui entender o erro que você descreveu e vou ficar atento aqui quando chegar nessa parte. Espero acabar em breve. Vou deixar sua issue aberta até eu publicar a versão com isso. 

Att

**Comment by EzequielHaccourt** [comment]
Consegui contornar da seguinte forma:

`app.get('/Userl',(req,res,next) => {
        // #swagger.tags = ['Users']
        // #swagger.description = 'Retorna a lista completa de usuarios'
        next()
    },global.Jwt,global.Log,global.Cors,global.ApiCache,PolicialController.viewAll)`

Encadeando middlewares até a função no controller, para o autogen funcionar tem que colocar as anotações na primeira função, caso contrario o autogen coloca na Tag default e deixa sem parâmetros e demais informações

**Comment by davibaltar** [comment]
Legal! E o que estou implementando agora ele vai identificar a função que está sendo referenciada. No seu exemplo, ele vai conseguir ler o conteudo da sua UserController.viewAll, ou seja, as tags '#swagger' vão poder ficar no seu controller. Mas massa a solução que vc encontrou pra contornar o problema por agora!

**Comment by davibaltar** [comment]
Ezequiel, publiquei uma versão que faz o reconhecimento das rotas. Por enquanto, o array de middlewares ainda não é reconhecido; o módulo só reconhece um middleware por endpoint. Na próximo versão tentarei tratar isso. Mas a referencia de funções e o Router já estão na versão 2.0.0. Qualquer problema, abre uma issue aí. Att

**Comment by EzequielHaccourt** [comment]
Show de bola, vou testar aqui e já te dou um feedback!
