### ISSUE TITLE
Problema ao definir $ em array para informar que é obrigatório.

### ISSUE THREAD

**Issue by RafaelIsmayle** [davibaltar/swagger-autogen#40]
Olá a todos! Primeiramente peço desculpas por trazer essa dúvida em português, mas acredito que assim conseguirei me expressar melhor.
Estou com a seguinte dificuldade:
Criei uma Definition que contém tanto strings quanto um array, 
Porém quando vou informar que trata-se de um item obrigatório e acrescento o “$”, não funciona para o array. Não tenho certeza se isso é um erro, ou se eu estou apenas fazendo da forma incorreta, poderiam me ajudar?

 
` AddUser: {
            $name: "Jhon Doe",
            $age: 29,
            about: ""
        },
        teste1: {
            $namespace: "meu-namespace",
            $cluster: "meu-cluster",
            $rdi: "RDI1234567890",
            $pods_list: ["meu-pod-001-000", "meu-pod-002-000"]
        }`

Dessa forma, na parte UI é apresentado o "$pods_list" ao invés de aparecer "pods_list *"

Desde já agradeço!

**Comment by davibaltar** [comment]
Oi @RafaelIsmayle. Obrigado por abrir a issue. E sem problemas com relação à linguagem.

Verifiquei seu caso aqui e vi que isso realmente é um bug no módulo. A sua declaração nas definitions está correta. Vou tratar esse erro e tentar subir na próxima versão. Farei o mais rápido possível.

Att

**Comment by RafaelIsmayle** [comment]
Entendi! Muito obrigado pelo retorno. Estarei no aguardo! E aproveito o momento para parabenizá-lo pelo módulo! Ajuda muito!

**Comment by davibaltar** [comment]
@RafaelIsmayle. Publiquei a versão 2.7.4 com essa correção. Faça um teste, por favor. E se o problema persistir, me avise.

**Comment by RafaelIsmayle** [comment]
Fiz a atualização para versão informada e deu tudo certo!! 
Muito obrigado!
