### ISSUE TITLE
Default host for swagger template

### ISSUE THREAD

**Issue by whlshy** [davibaltar/swagger-autogen#41]
Can do not give template for host?

So than I can use localhost or IP for swagger-ui in two host.

statics.js
```js
const TEMPLATE = {
    swagger: "2.0",
    info: {
        version: "1.0.0",
        title: "REST API",
        description: ""
    },
    // host: "localhost:3000",
    basePath: "/",
    tags: [],
    schemes: ['http'],
    securityDefinitions: undefined,
    consumes: [],
    produces: [],
    paths: {},
    definitions: {}
}
```

By the way,

can I update file in swagger-ui use this package?

**Comment by davibaltar** [comment]
Hi @whlshy.

I don't know if I got it right, but tell me if this is it:

1. Do you want to have the option (in the UI) to select between two hosts? Similar to what happens with "schemes"?

2. In the question about the update file in swagger-ui. Are you talking about modifying the .json file by the UI?

Tell me if I understand you correctly so that I can see an answer, please.

**Comment by whlshy** [comment]
Like I don't use same pc and I want to connect to api-server's api-doc, if I take out host

![image](https://user-images.githubusercontent.com/49122960/112476664-1a989d00-8dad-11eb-8fbe-a6339ab1003d.png)

![image](https://user-images.githubusercontent.com/49122960/112476178-9a723780-8dac-11eb-9905-d13ae4e8aea1.png)

 when I take out the host and your statics template do not have host,

and I can use two url in my api-doc page, I don't need to setup the host. (e.g. localhost:5000 & 10.21.20.109:5000)

![image](https://user-images.githubusercontent.com/49122960/112476418-d5746b00-8dac-11eb-9420-863e03dca59c.png)

![image](https://user-images.githubusercontent.com/49122960/112476473-e4f3b400-8dac-11eb-96d2-871a3d98dba8.png)

---------------------------------

If your static have host, I should write host to cover your statics host,

![image](https://user-images.githubusercontent.com/49122960/112476710-271cf580-8dad-11eb-9210-152c34265f53.png)

![image](https://user-images.githubusercontent.com/49122960/112476800-4025a680-8dad-11eb-96dd-7653ccbe5598.png)

Now, if I don't use api-server's pc, I can't use this swagger document because use the specify host

![image](https://user-images.githubusercontent.com/49122960/112478448-fccc3780-8dae-11eb-85ce-baab3f2f8dff.png)

**Comment by davibaltar** [comment]
oh yes, now I think understand @whlshy. Well, I thought a way to do that. For example, if it is passed "host: null", it will be missing from the .json file. What do you think?

In your case, would be like this:

```
const doc = {
    info: {
        ...
    },
    host: null,
    schemes: ['http'],
    ...
}
```

And with that, the "host" would be missing in the .json file. If this solution suits you, tell me, that I will implement it. And if I got it wrong, for correcting me too, please.

**Comment by whlshy** [comment]
OK, I originally think is if I can unnecessary write host in doc, but you can also.

Thank you very much @davibaltar !

**Comment by davibaltar** [comment]
Ok @whlshy.

In this case, not writing the "host" causing the removal of the "host" in the .json, some projects that already use the default value localhost:3000 without informing the "host" parameter, would have problems. So, to maintain compatibility with these projects that already work that way, it will be necessary.

I will implement the "host: null" as soon as possible.

**Comment by whlshy** [comment]
OK @davibaltar.
I know what you mean, looking forward to your project more perfect!👍

**Comment by davibaltar** [comment]
The version 2.7.6 has implemented this. To omit any of the attributes in the _.json_ file, just assign the value **null** to the specified attribute in the **doc**. Any problem, let me know.
