### ISSUE TITLE
swagger-autogen recognises only the last endpoint (separate files)

### ISSUE THREAD

**Issue by davibaltar** [davibaltar/swagger-autogen#46]
**Author:** @NikolaLukic1

Is this issue related to not recognising the same paths on router?

Example:
I have router.post(/item) and router.delete(/item).

Result in swagger_output file is always the last file in endpoints array. 
```
router.post(
    '/nutrition/meal',
    validate({body: dailyMealSchema}),
    /*
    #swagger.description = 'Add meal daily nutrition endpoint' 
    #swagger.tags = ['DailyNutrition']

    #swagger.parameters['body'] = {
            in: 'body',
            description: 'add daily meal body',
            required: true,
            schema: { $ref: "#/definitions/AddDailyMeal" }
    } 

    #swagger.responses[200] = { 
    schema: { "$ref": "#/definitions/AddDailyMealResponse" },
    description: "Add daily meal response" } */
    controller.AddMeal
)

router.delete(
    '/nutrition/meal',
    deleteMealSchema,
    /*
    #swagger.description = 'Delete meal endpoint' 
    #swagger.tags = ['DailyNutrition']
    #swagger.parameters['id'] = { description: 'Daily nutrition id' }
    #swagger.parameters['mealGuid'] = { description: 'Meal guid' }

    #swagger.responses[200] = { 
    schema: { "$ref": "#/definitions/DeleteMealResponse" },
    description: "Delete meal response" } */
    controller.DeleteMeal
)
```
These are in separate files.
So when i import these endpoints, swagger autogen recognises only the last endpoint in this case.

Am I doing something wrong?

_Originally posted by @NikolaLukic1 in https://github.com/davibaltar/swagger-autogen/issues/35#issuecomment-811027322_

**Comment by davibaltar** [comment]
Hi @NikolaLukic1. Thank you for opening the issue.

I'll try to reproduce this problem here to handle it. If I can't reproduce, I'll tell you.

**Comment by davibaltar** [comment]
Hi @NikolaLukic1. Thank you for opening the issue. I cannot reproduce this problem here. 

Could you submit a simple project in your repository that reproduces just this problems and send me the link?

**Comment by NikolaLukic1** [comment]
Here is a example repo. Thanks for your hard work.

https://github.com/NikolaLukic1/swaggerIssue/tree/master

**Comment by davibaltar** [comment]
The version 2.7.8 has fixed this. If the problem persists, let me know. 

NOTE: Some TypeScript features are not recognized yet.

**Comment by yolave** [comment]
Hi @davibaltar ! 

I'm still experiencing this problem in my project, even using the version `2.7.8`. I have 2 services in different files but both of them are referencing the same end-point, one using `POST` and another using `PUT`.

When I generate the documentation, only appears the last one declared in the `swagger.js` file.

May am I doing something wrong?

**Comment by davibaltar** [comment]
Hi @yolave. 

Could you submit a simple project in your repository that reproduces just this problems and send me the link?

That way it is easier to identify the problem.

**Comment by yolave** [comment]
hi again @davibaltar and sorry for the delay. I'll share an example as soon as possible

**Comment by LuisLenta** [comment]
Hi @davibaltar . I'm still experiencing this problem in my project (version 2.9.3). I think the problem occurs in line 109 of swagger-autogen.js file. 
In the image you can see the new paths to add to a new file. As some are repeated, they are not copied correctly, leaving only the last one. For example, /getById or /getAll of the obj object replace the existing ones in objDoc.paths.
In the second image you can see how I declare the paths.

I hope my explanation is understood.

![bug](https://user-images.githubusercontent.com/26776707/127520526-ed55aa5e-91c0-4931-b83a-de05455e56ca.png)
![WhatsApp Image 2021-07-29 at 13 29 16](https://user-images.githubusercontent.com/26776707/127529913-4c5031cd-0f51-44d4-ab72-e39c5de54340.jpeg)

**Comment by davibaltar** [comment]
Hi @LuisLenta! Sorry for the delay. Thank you for the explanation. 

I have a doubt: Do you have two endpoints with the same name in different file? if yes, how do you call them in the swagger.js file?

Because, if there are more than one file with the same endpoint name, the module will be replace the oldest. To avoid this, you can pass the root file that content the route.

**Comment by LuisLenta** [comment]
Thanks for the response. 
Yes, i have two endpoints with the same name in different file. 
In the image you can see how i call in swagger.js file. For example, the file './routes/stops.js' and './routes/routes.js' have the same endpoit called '/getById'.  
![Dibujo2](https://user-images.githubusercontent.com/26776707/128729158-603b715a-4d28-4244-868e-21ce15ac810c.png)

**Comment by LuisLenta** [comment]
Hello! 

I solve the problem adding   
// #swagger.paths = ['/agencies/getAll']
as  a comment in each endpoint

For example
![swagger](https://user-images.githubusercontent.com/26776707/139542541-2ef5c901-1505-40c0-b97b-6fbd8ac21920.png)

Thanks for everything

**Comment by davibaltar** [comment]
Hi @LuisLenta. Thanks for the feedback. Yes, for this case, if the swagger-autogen cannot recognises your route file, this is the only way to solve for now.

But thanks, because other people can have the same problem and now this post can help them.
