### ISSUE TITLE
Models How to turn off the display or remove

### ISSUE THREAD

**Issue by hsiangfeng** [davibaltar/swagger-autogen#48]
My users don’t need to see Models.

So can this option be turned off?

Or can I only write CSS display: none?

oh,

This is a nice feature, so I also wrote a traditional Chinese teaching article :)

**Comment by hsiangfeng** [comment]
Hi, @davibaltar 
it's him!

**Comment by davibaltar** [comment]
yes, @hsiangfeng. There are two ways to do this:

**CSS:**  
```js
const swaggerUi = require('swagger-ui-express')
...
app.use('/doc', swaggerUi.serve, swaggerUi.setup(swaggerFile, { customCss: '.swagger-ui .models { display: none }'}))
```

**Options:**  
```js
const swaggerUi = require('swagger-ui-express')
...
app.use('/doc', swaggerUi.serve, swaggerUi.setup(swaggerFile, false, { defaultModelsExpandDepth: -1 }))
```

Try this and tell me if it doesn't work.

**Comment by hsiangfeng** [comment]
Hi, @davibaltar
ok, is working!
but...hope build swagger_out.json can don't show models.

Because I tried to turn him into HTML.

**Comment by davibaltar** [comment]
@hsiangfeng, I couldn't find a solution for that. But, as I don't know if that is possible, I'll keep the issue open for some time, because maybe someone see this and know a way to do it.

**Comment by davibaltar** [comment]
Hi @hsiangfeng. I still haven't found a solution for this. For now, I'll close the issue. But if I find a solution, I'll post here.
