### ISSUE TITLE
When a router under the function not work

### ISSUE THREAD

**Issue by whlshy** [davibaltar/swagger-autogen#49]
![image](https://user-images.githubusercontent.com/49122960/114261618-1fe12300-9a0e-11eb-9ccd-0fd7a1789ce4.png)

I can't see **/file/uploadIMG** in swagger ui

![image](https://user-images.githubusercontent.com/49122960/114261666-70f11700-9a0e-11eb-8d10-8b3f86a35971.png)

And when I open the annotation it's work.

**Comment by davibaltar** [comment]
Hi @whlshy. Thank you for opening the issue. 

This is a bug. I'll handle it as soon as possible.

**Comment by davibaltar** [comment]
The version 2.7.9 has fixed this. If the problem persists, let me know.
