### ISSUE TITLE
Issue with Router integration

### ISSUE THREAD

**Issue by shemama2** [davibaltar/swagger-autogen#5]
Hi,

We have tested this library with typescript and identified two issues with this library,

1. When we have a middleware used in the router, the swagger-autogen is not able to read the router and generate endpoints.
    Eg:  ```` router.use(middleware) ```` when the router has this piece of code the swagger-autogen fails to generate swagger.

2. Swagger-autogen expects the route path to be explicitly given for all the request method type. 
    It, fails to work when we use a path and define more than one request methods for the same route.

Eg: Swagger-autogen Expects:

>     router.route('/api/v1/home').get({}) 
>     router.route('/api/v1/home').post({})  

    
    Fails when,

     router.route('/api/v1/home')
    .get({}) 
    .post({})

**Comment by davibaltar** [comment]
Hello.

About the items:

1. The module is not yet fully compatible with Typescript. I'm working on it these days, implementing route recognition, imports, etc. for Typescript. I hope to finish soon ..

2. I didn't really look at this case. I'll put it on my todo list.

I will try to put these two items in the next version.

Thanks!

**Comment by davibaltar** [comment]
The version 2.1.0 focused on solving this issue and implementing other features. If you have problems, open a new issue.

**Comment by shemama2** [comment]
That was awesome. Thanks for solving this problem!
