### ISSUE TITLE
Problema ao realizar request

### ISSUE THREAD

**Issue by aylonMuramatsu** [davibaltar/swagger-autogen#51]
Bom dia ! tudo bem? 
Minhas requisições que possuem um array como parâmetro não são executadas, não achei nada sobre na documentação seria um bug ? ou estou fazendo errado? 
![image](https://user-images.githubusercontent.com/28609474/116255297-7ce81300-a748-11eb-858b-9dcd4f53551f.png)
A propriedade "items" é um array se eu tento passar e clico em execute nada acontece

**Comment by davibaltar** [comment]
Oi @aylonMuramatsu. Tudo joia!

Você não está fazendo errado. Nesse caso, o problema não está relacionado com o módulo swagger-autogen em si, e sim com o SwaggerUI. O módulo só gera o arquivo .json. Tanto que se você pegar o conteúdo de saída gerado no arquivo .json e colar no próprio site do swagger ([editor.swagger.io](https://editor.swagger.io)), esse problema também ocorrerá. O que acontece é que o swagger-autogen não consegue (pelo menos ainda) identificar o tipo dos parâmetros que são recebidos no body. Por isso, o tipo 'string' é atribuído juntamente com um valor de exemplo "any" por padrão. Quando você manda executar uma requisição pela UI, ela faz uma validação de tipos nesse momento, e por isso que não funciona, porque ela espera uma 'string'.

Para contornar isso, você vai precisar declarar os parâmetros do seu _body_ como visto aqui: [https://www.npmjs.com/package/swagger-autogen#parameters](https://www.npmjs.com/package/swagger-autogen#parameters)

Espero que num futuro próximo o Swagger tenha uma opção para desativar essa validação, porque já tive outra issue aberta aqui sobre esse tema. 

Espero que tenha ficado claro. Vou fechar a issue por estar fora do escopo do nosso módulo. Mas qualquer outro problema, pode falar. 

Att

**Comment by davibaltar** [comment]
@aylonMuramatsu, acho consegui contornar o problema. Publiquei na versão 2.8.1. 

Att

**Comment by aylonMuramatsu** [comment]
@davibaltar Muito obrigado! irei testar! obrigado pela atenção!
