### ISSUE TITLE
implementing swagger tags and parameter with asyncHandler

### ISSUE THREAD

**Issue by Abderrahmenla** [davibaltar/swagger-autogen#56]
I'm issuing this problem in my node project (see the link below for my proshop project).
swagger can't read :
 
// #swagger.tags = ['Orders']
  // #swagger.description = 'Endpoint for placing an order.'

in my ./backend/controllers/orderController.js file (maybe because I'm using express-async-handler)see the links below:

proshopapp96.herokuapp.com/api-docs/
[Proshop project](https://github.com/Abderrahmenla/proshop)

**Comment by davibaltar** [comment]
Hi @Abderrahmenla. Thank you for opening the issue. 

This is a bug. I'll handle it as soon as possible.

**Comment by davibaltar** [comment]
Hi @Abderrahmenla! The version 2.8.2 has fixed this. If the problem persists, let me know.

**Comment by Abderrahmenla** [comment]
it's working fine now! good job!
