### ISSUE TITLE
Bearer authentification

### ISSUE THREAD

**Issue by Abderrahmenla** [davibaltar/swagger-autogen#57]
swagger-autogen doesn't detect my Bearer token to authorize accessing specific endpoints,
I did the the security definition in the swagger file :
  securityDefinitions: {
    Bearer: {
      type: 'apiKey',
      name: 'Authorization',
      in: 'header',
    },
  },
and 
  /* #swagger.security = [{
               "Bearer": []
        }] */
in the route but still doesn't detect it for further details here's the project repo that I'm working on : 

[Proshop live app](http://proshopapp96.herokuapp.com/api-docs/)
[Proshop github repo](https://github.com/Abderrahmenla/proshop)
see ./backend/controllers/ and swagger.js

**Comment by Abderrahmenla** [comment]
My bad guys, I fixed a typo!it works fine

**Comment by davibaltar** [comment]
Hi @Abderrahmenla. No problems. There is an open issue about it here and I couldn't test. I'll quote that issue there, but first, I need to know if the:

```
securityDefinitions: {
    Bearer: {
        type: 'apiKey',
        name: 'Authorization',
        in: 'header'
    }
}
```
and
```
/* #swagger.security = [{
    "Bearer": []
}] */
```

It work? or did you need to do any more adjustments?

**Comment by Abderrahmenla** [comment]
yeap it worked fine,I put "Bearer jwt_token"  in "authorize",here you can check "http://proshopapp96.herokuapp.com/api-docs",

**Comment by davibaltar** [comment]
Greate! Thanks!
