### ISSUE TITLE
Body object shoud be request body?

### ISSUE THREAD

**Issue by SergioSuarezDev** [davibaltar/swagger-autogen#60]
Hi, 

I'm trying to test a json object in body but it not working following your instructions:

Check my endpoint definition: 
<img width="513" alt="Captura de pantalla 2021-05-30 a las 6 33 56" src="https://user-images.githubusercontent.com/3636232/120092130-09ec0680-c111-11eb-80ba-1cbeb87f175a.png">

Here the result:
<img width="778" alt="Captura de pantalla 2021-05-30 a las 6 34 29" src="https://user-images.githubusercontent.com/3636232/120092148-24be7b00-c111-11eb-8ea3-07e778c5580e.png">

But using directly the swagger ui in other project, body is different (working well)

<img width="772" alt="Captura de pantalla 2021-05-30 a las 6 32 11" src="https://user-images.githubusercontent.com/3636232/120092169-43bd0d00-c111-11eb-92fa-4af08a029fa0.png">

thanks in advance!

**Comment by davibaltar** [comment]
Hi @SergioSuarezDev. Thank you for opening the issue.

Could you submit a simple project in your repository that reproduces just this problems and send me the link? 

That way it is easier to identify the problem.

**Comment by SergioSuarezDev** [comment]
Basically for the request body to be generated correctly in swagger, it should be like this. (part of my swagger_definition.json)


```
    "/user/login": {
      "post": {
        "tags": [
          "User"
        ],
        "description": "User login",
        **"requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/definitions/UserLogin"
              }
            }
          }**
        },
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    }
```

Hope this code helps

**Comment by davibaltar** [comment]
Thank you, @SergioSuarezDev. I'll check this case as soon as possible.

**Comment by PhillRoyle** [comment]
Hi @davibaltar 
Any progress on this?
I'm running into the same issue, defining a `requestBody` similar to to @SergioSuarezDev , and when I run auto-gen, it's converted into parameters. I guess it's something in `getQueryAndBody` parsing the json and asuming eveything is a parameter?
Those parameters display properly in the UI, but I'm unable to execute the endpoint.

**Comment by SergioSuarezDev** [comment]
Would be nice solve this issue soon ;-)

**Comment by PhillRoyle** [comment]
actually, a little more testing (sorry) and I think 
> when I run auto-gen, it's converted into parameters

isn't true. Autogen had just automatically inferred the params on the endpoint I thought that had happened on. Looks like `requestBody` is just ignored.

Sorry for the false steer.

**Comment by davibaltar** [comment]
Hi @SergioSuarezDev and @PhillRoyle. 

The version 2.11.0 has implemented this feature. This is new feature, so it may contain bugs. I ask you to test and if you have any problems, let me know. To use this functionality, do the following:

NOTE: It's necessary to enable the OpenAPI v3 in the options:

If you're using CommonJS:
```js
const swaggerAutogen = require('swagger-autogen')({openapi: '3.0.0'})
```

Or if you're using ES modules:
```js
import swaggerAutogen from 'swagger-autogen';
// ...
swaggerAutogen({openapi: '3.0.0'})(outputFile, endpointsFiles, doc)
```

**Endpoint example:** 
```js
app.post('/path', (req, res, next) => {

    /*	#swagger.requestBody = {
            required: true,
            content: {
                "application/json": {
                    schema: {
                        $ref: "#/definitions/User"
                    }  
                },
                "application/xml": {
                    schema: {
                        $ref: "#/definitions/User"
                    }  
                }
            }
    } */

})
```

If the problem persists, open this issue again.

**Comment by PhillRoyle** [comment]
Works a treat, thanks very much!
 You're a genius!

**Comment by SergioSuarezDev** [comment]
Works fine! Thanks

**Comment by rlawisch** [comment]
@davibaltar using `#swagger.requestBody` works, thanks a lot, but `obj` is still being listed in the Parameters section (which gets very confusing/misleading in the `Try it out`):
![obj-params](https://user-images.githubusercontent.com/25728000/127899172-1e8fd37c-d3dd-4137-b2ff-95fe7849fde1.PNG)

**Comment by davibaltar** [comment]
Hi @rlawisch! I hadn't thought about this case. This is a bug! 

To workaround this, I'll disable the "automatic body recognition" when the "#swagger.requestBody" is present.

**Comment by davibaltar** [comment]
The version 2.11.2 has fixed this. If the problem persists, let me know.
