### ISSUE TITLE
List of routers not working

### ISSUE THREAD

**Issue by carllau999** [davibaltar/swagger-autogen#61]
If I create multiple express Routers, under the same name space it stops working.
For example,

```
import { Router } from 'express'
import user from './user.js'
import data from './data.js'

const router = Router()

router.use('/server', [user, data])
```

This will generate an empty swagger doc.

**Comment by davibaltar** [comment]
Hi @carllau999. Thank you for opening the issue. 

I'll handle it as soon as possible.

**Comment by davibaltar** [comment]
The version 2.9.2 has fixed this. If the problem persists, let me know.
