### ISSUE TITLE
swagger autogen can't read my controllers

### ISSUE THREAD

**Issue by Abderrahmenla** [davibaltar/swagger-autogen#64]
I'm working on a private project where swagger can't read my controllers: here's the structure of the folder : 
config
controllers: userController.js
middlewares
models
routes
app.js
server.js
package.json
swagger_output.json
swagger.js
![Screenshot_2021-06-19 Swagger UI](https://user-images.githubusercontent.com/29304794/122629887-fef51800-d0b7-11eb-988b-246f75ddd009.png)

these comments ain't detected :
// #swagger.tags = ['Users']
// #swagger.description = 'Endpoint for placing an order.'

in my ./controllers/orderController.js file,I guess this issue is due because of the folder structure
here's what I have in my swagger.js file : 
const outputFile = './swagger_output.json';
const endpointsFiles = ['./server.js'];

swaggerAutogen()(outputFile, endpointsFiles, doc).then(async () => {
  await import('./server.js');
});

**Comment by davibaltar** [comment]
Hi @Abderrahmenla. Thank you for opening the issue. 

I cannot reproduce this problem here. Could you submit a simple project in your repository that reproduces just this problems and send me the link?

That way it is easier to identify the problem.

**Comment by davibaltar** [comment]
In the swagger.js file, instead of:

```js
const endpointsFiles = ['./server.js'];
```

change to:

```js
const endpointsFiles = ['./app.js'];
```

It worked fine here. Try it, and let me know if the problem persists.

**Comment by bralandealmeida** [comment]
Hello, I have been facing the same problem. When I put the http.ts it doesn't return all the routes and the ones that come back don't return with the parameters. Could someone give me a light?

**Comment by davibaltar** [comment]
Hi @bralandealmeida!

Could you submit a simple project in your repository that reproduces this problems and send me the link?

That way it is easier to identify the problem.

**Comment by bralandealmeida** [comment]
> Hi @bralandealmeida!
> 
> Could you submit a simple project in your repository that reproduces this problems and send me the link?
> 
> That way it is easier to identify the problem.

Okay. I've uploaded an example that has more or less the same structure as the one I'm using in the other project.

https://github.com/bralandealmeida/swagger-example

**Comment by davibaltar** [comment]
@bralandealmeida, the version 2.15.0 has fixed this, but the features about TypeScript are still in progress. 

If the problem persists, let me know.
