### ISSUE TITLE
Route disapear when there is one middleware with parameters

### ISSUE THREAD

**Issue by LoicMoerman** [davibaltar/swagger-autogen#65]
Hello,

I'm trying to chain two middlewares like this :

`routes.use(
  "/users",
  authenticationMiddleware,
  hasRole(["technicalService", "saleDepartment"]),
  userRouter
);`

Unfortunately /users totaly disapear in the generated documentation. However it works when there is only one middleware.

Thanks in advance ! :)

**Comment by davibaltar** [comment]
Hi @LoicMoerman. Thank you for opening the issue.

Could you submit a simple project in your repository that reproduces this problems and send me the link?

That way it is easier to debug and identify the problem.

**Comment by LoicMoerman** [comment]
Hey, 
I tried my best to make it clear for you.
Juste start the app and go to localhost:3000/doc 
Then uncomment the line in src/routes/index.ts and relaunch the app two times to regenerate the doc.
Then see User disapear
https://github.com/LoicMoerman/IssueWithSwaggerAutogen

**Comment by davibaltar** [comment]
Great, @LoicMoerman! Thanks! 

I'll fix this as soon as possible.

**Comment by LoicMoerman** [comment]
Re, I just noticed that only middlewares with parameters cause the issue, so the title of the issue is wrong.

**Comment by davibaltar** [comment]
The version 2.10.1 has fixed this. If the problem persists, let me know.
