### ISSUE TITLE
Swagger-Autogen and Multer: Multiform data

### ISSUE THREAD

**Issue by PauloFavero** [davibaltar/swagger-autogen#66]
Hi Davi,

I have an endpoint used for file uploading. I'm using express for the router and multer as a middleware for the upload task. 
My upload endpoint should receive two files. Multer inserts the files in `req. files`. How can I set up swagger to recognize it?

Here is what I am trying to do.

```
const controller = (req, res) => {
  // #swagger.tags = ['Reconcile']
  // #swagger.summary = 'Your summary here'
  // #swagger.description = 'My description'
  // #swagger.consumes = ['multipart/form-data']
  // #swagger.produces = ['application/json']
  /*  #swagger.parameters['file_A'] = {
        in: 'files',
        type: 'file',
        required: 'true',
        description: 'File data',
  } */
  /*  #swagger.parameters['file_B'] = {
        in: 'files',
        type: 'file',
        required: 'true',
        description: 'File data',
  } */

  const files = req.files;
  console.log(files);
}
```

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/26371434/123527574-2e5ae480-d6b7-11eb-90b6-7b1fed8968b4.png">

Thanks,
Paulo

**Comment by davibaltar** [comment]
Hi @PauloFavero! Thank you for opening the issue.

Just to make sure I understood what you said, the documentation was generated by the swagger-autogen, but when you try to upload your files by the swagger UI, it doesn't work, is that correct?

**Comment by PauloFavero** [comment]
Yes, that is correct. `req.files` is undefined in this case. Probably I am missing something.

**Comment by davibaltar** [comment]
Ok. Could you submit a simple project in your repository that reproduces this problems and send me the link?

That way it is easier to debug and identify the problem.

**Comment by PauloFavero** [comment]
I wrote a small project where you can test the mentioned behavior.
Please see the [Swagger Test Repository](https://github.com/PauloFavero/SwaggerTest).

I hope it helps. 

Thanks,
Paulo

**Comment by davibaltar** [comment]
Thanks for the code, @PauloFavero. Trying here..

in **route.js** file:

```js
router.post("/test", uploader.array("transactions", 2), (req, res) => {
  // #swagger.tags = ['Test']
  // #swagger.summary = 'Test Endpoints'
  // #swagger.description = 'Upload two csv files.'
  // #swagger.consumes = ['multipart/form-data']
  // #swagger.produces = ['application/json']
  /*  #swagger.parameters['transactions'] = {
          in: 'formData',
          type: 'array',
          required: true,
          description: 'Transactions file',
          collectionFormat: 'multi',
          items: { type: 'file' }
  } */

  const files = req.files;

  console.log(files);
  console.log(req);

  try {
    console.log(files.map((file) => file));
    res.status(200).json({ message: "File Parsed with success" });
  } catch (error) {
    console.log(error);
    res.status(500).send({ error: error.message });
  }
});
```

here, it work fine! The _req.files_ received the 2 files. Try it and let me know if doesn't work.

**Comment by PauloFavero** [comment]
Thanks Davi! 

It works!  I will close the issue.
