### ISSUE TITLE
Set securityDefinitions for every endpoint

### ISSUE THREAD

**Issue by DanMossa** [davibaltar/swagger-autogen#68]
Hello!

I was wondering if there is an option to enable securityDefinitions for every endpoint and then manually disable them per endpoint?

Thanks!

**Comment by davibaltar** [comment]
Hi @DanMossa. Thank you for the suggestion!

I will check the possibility of implementing this.

**Comment by davibaltar** [comment]
The version 2.18.0 has implemented this.

Declare the security in the route root middleware, such as:

```js
...
app.use('/v1', routesV1
    /* #swagger.security = [{
        "apiKeyAuth": []
    }] */
...
```

And to manually disable security for a specific endpoint that belongs to '/v1', do the following: 
```js
app.get('/path', (req, res) => {
    ...
    // #swagger.security = null
    ...
})
```

See more about it here: [Properties Inheritance](https://github.com/davibaltar/swagger-autogen#properties-inheritance)

If it doesn't work, let me know, please.
