### ISSUE TITLE
Route Recognition - Issue with regular expressions

### ISSUE THREAD

**Issue by pratikIT95** [davibaltar/swagger-autogen#7]
First of all, thank you for building such a useful library, it really helps keep my swagger flow cleaner.

The issue I'm facing is that when I try to use swagger-autogen with routes that have regular expressions, the entire recognition gets bugged out.

For example : -

`router.get('hello/:id([0-9]{1,})`

results in an output like this :- 

```json
"/_undefined_path_0x17c": {
      "get": {
        "tags": [
          {
            "name": "Endpoints without path or method"
          }
        ],
        "description": "",
        "parameters": [],
        "responses": {}
      }
    },
```

While,

`router.get('hello/:id)`

results in an output like this :-

```json
 "/hello/{id}": {
      "get": {
        "tags": [],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {}
      },
```

Can you please help in resolving this?

**Comment by davibaltar** [comment]
Hi pratikIT95, glad the library has been useful for you! 

About the regular expression in the routes, I hadn't paid attention to this case. I'll put it in my todo list and try to upload it in the next version. I hope to do soon.

I'll keep the issue open until the problem is solved.

**Comment by davibaltar** [comment]
Hi @pratikIT95. 

I am implementing this case of regular expression here. As I never used regex on my routes, I was in doubt: in the case of your example, when I pass a path in my code equal to:

`router.get('hello/:id([0-9]{1,})', foo...)`

the expected result in the swagger will be:

`/hello/{id([0-9]{1,})}`

that right? If not, tell me, please.

**Comment by pratikIT95** [comment]
> Hi @pratikIT95.
> 
> I am implementing this case of regular expression here. As I never used regex on my routes, I was in doubt: in the case of your example, when I pass a path in my code equal to:
> 
> `router.get('hello/:id([0-9]{1,})', foo...)`
> 
> the expected result in the swagger will be:
> 
> `/hello/{id([0-9]{1,})}`
> 
> that right? If not, tell me, please.

Yes @davibaltar , that is my exact use case 😃

**Comment by davibaltar** [comment]
Great @pratikIT95! Version 2.2.0 implemented this feature.
