### ISSUE TITLE
Quotation marks issue - mixing " ' "

### ISSUE THREAD

**Issue by ryordanov** [davibaltar/swagger-autogen#74]
There is an issue here:
https://github.com/davibaltar/swagger-autogen/blob/284adee699a11c933fd22dd3653f43da8b7932b0/src/utils.js#L71-L93

If you have two methods in your routes and first of them have mixed quotes(single and double), the swagger definition of the last method is being used for both of them.

```
fetch: async (req, res) => {
        /*  #swagger.parameters['obj'] = {
                in: 'body', ...
            }
        */
...
result = { message: "Blah blah's blah"};     <----------
...
},
```

```
fetchViewIds: async (req, res) => {
      // #swagger.summary = 'Your summary here'
      /*  #swagger.parameters['obj'] = {
              in: 'body', ...
          }
      */
...
},
```

![2021-07-24_23-36](https://user-images.githubusercontent.com/2446094/126880540-e5c41094-33ba-41bb-8507-a99c64860cab.png)

**Comment by davibaltar** [comment]
Hi @ryordanov. Thank you for opening the issue.

I'll fix this as soon as possible.

**Comment by davibaltar** [comment]
The version 2.11.1 has fixed this bug. If the problem persists, let me know.
