### ISSUE TITLE
headers are not recognized by the autogen

### ISSUE THREAD

**Issue by MosheLOptimove** [davibaltar/swagger-autogen#78]
Hi, 

I have an API where one of the required inputs is an header action ("X-UNIQUE-ID"). I used express build in function:
`const unique = req.header("X-UNIQUE-ID");`
but the auto gen didn't find and added it to the swagger output.

Is there a way to add it without a comment? I tried using headers['X-UNIQUE-ID'] as well, but same result.

Thanks,
M

**Comment by davibaltar** [comment]
Hi @MosheLOptimove! Thank you for opening the issue. 

For now, auto gen doesn't recognize this case, but I'll try to handle it like a feature in a future version.

Thanks!

**Comment by davibaltar** [comment]
The version 2.17.0 has implemented this feature. Using `... headers['X-UNIQUE-ID']`, the lib will recognize the header parameter automatically. Any problems, let me know.

**Comment by MosheLOptimove** [comment]
Thanks @davibaltar

**Comment by MosheLOptimove** [comment]
Hi @davibaltar,

I just tried the new feature, but didn't get the result you mentioned.

```
app.post('/cleanup/resource', async (req, res) => {
    // #swagger.tags = ['Cleanup']
    res.set('Content-Type', 'application/json');
    const tenantId = req.header('X-UNIQUE-ID');
    const logParams = { tenant: tenantId };

    try {
        // work
        res.status(204).send();
    }
    catch (err) {
        // error
        res.status(500).send(err);
    }
});
```

And the swagger file resulted in the auto-gen was:
```
"/cleanup/resource": {
    "post": {
    "tags": [
        "Cleanup"
    ],
    "description": "",
    "parameters": [],
    "responses": {
        "204": {
             "description": "No Content"
        },
        "500": {
             "description": "Internal Server Error"
        }
    }
}
```

It's not exactly as you wrote (...headers[...]), but I've seen in the commit that you referenced to `.headers` as well.

Any idea why it happens? Version is up to date (2.17.0).

Thanks,
M

**Comment by davibaltar** [comment]
Hi @MosheLOptimove! Thanks for the report. 

The version 2.17.1 has made some fixes about it. 

Try this version, and let me know if the problem persists, please.
