### ISSUE TITLE
Adding Bearer Token

### ISSUE THREAD

**Issue by doruksahin** [davibaltar/swagger-autogen#81]
I am trying to add bearer token field to swagger ui.
I couldn't find any example about it.
I tried this:

router.delete("/:auctionId", ensureToken, async (req, res) => {
    // #swagger.tags = ['Auctions']
    /* #swagger.security = [{
        "Bearer": []
    }] */
    ....
    
However that won't work. 
In UI, there is a lock symbol next to this item but nothing happens when i click on it.
Can you help me with this please?

**Comment by davibaltar** [comment]
Hi @doruksahin! Thank you for opening the issue. 

There is a closed issue about this subject. See it here: [https://github.com/davibaltar/swagger-autogen/issues/57](https://github.com/davibaltar/swagger-autogen/issues/57)

And there is a reference in the official documentation here: [https://www.npmjs.com/package/swagger-autogen#api-keys-token-example](https://www.npmjs.com/package/swagger-autogen#api-keys-token-example)

But, if the two links above don't help you, let me know, please.

**Comment by doruksahin** [comment]
Hey @davibaltar. Thank you for your help. Also, thank you for your library!
