### ISSUE TITLE
$ref of undefined error when using React Router params

### ISSUE THREAD

**Issue by dbeacham15** [davibaltar/swagger-autogen#94]
```
// Causes build to break
router.get('/:categoryId', categoryCtrl.getCategory)

// Works just fine

router.get('/categories', .....)
```

Anytime I try to generate the docs using openapi 3.0 and the route has a parameter, the build fails.  If I switch to using swagger 2.0 default, it works fine.   I need to use the openapi for JWT BearerToken security testing.  

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property '$ref' of undefined
    at Object.getPathParameters (/node_modules/swagger-autogen/src/handle-data.js:959:73)
```

**Comment by davibaltar** [comment]
Hi @dbeacham15! Thank you for opening the issue!

Could you submit a sample project that reproduces only this problem? That way is more easy to identify and treat it.

Thanks!

**Comment by davibaltar** [comment]
The version 2.12.6 has fixed this. If the problem persists, let me know.
