### ISSUE TITLE
RequestBody not being generated for PUT, POST requests OpenAPI: 3.0.0

### ISSUE THREAD

**Issue by irzakamran99** [davibaltar/swagger-autogen#95]
Hello @davibaltar, 

Thanks for creating this wonderful library.

When I run swagger auto-gen to generate the JSON file, it produces body and form parameters that have been replaced in OpenAPI 3.0.0 with [requestBody](https://swagger.io/docs/specification/describing-request-body/).  
I have set the version to 3.0.0 like this 
`const swaggerAutogen = require("swagger-autogen")({ openapi: "3.0.0" });
`
It should produce requestBody in the JSON file not body parameters for PUT, POST requests.

Because requestBody does not exist in the paths in the JSON file, the SwaggerUI does not send requestBody to the API. Can you please help me solve this issue? 

Thanks in advance.

**Comment by davibaltar** [comment]
Hi @irzakamran99! Thank you for opening the issue. 

Sorry for any problem with the lib when it uses openapi v3. This feature is in progress. About the requestBody in the JSON by default when the lib uses openapi v3, I'll try to fix it as soon as possible. Probably in the next version!

Thanks a lot for this report.

**Comment by irzakamran99** [comment]
Thanks for the quick response. Do you know when we can expect the next version to be released? I have encountered another [problem](https://github.com/davibaltar/swagger-autogen/issues/96) , I hope you can help resolve that as well. 

Thanks in advance!

**Comment by davibaltar** [comment]
Hi @irzakamran99! I hope to fix the #95 and #96, and release them in the next version next weekend.  

Any problems I find, I'll post it here.

**Comment by davibaltar** [comment]
The version 2.12.7 has fixed this. If the problem persists, let me know.
