### ISSUE TITLE
Incorrectly Recognises hasOwnProperty as a Body Parameter

### ISSUE THREAD

**Issue by irzakamran99** [davibaltar/swagger-autogen#96]
Hello @davibaltar!

When I run swagger auto-gen to generate the JSON file, it creates POST and PUT body objects with hasOwnProperty as a parameter. 

<img width="1260" alt="Screen Shot 2021-11-16 at 6 57 22 PM" src="https://user-images.githubusercontent.com/86774070/142002726-a88032cc-10e1-47a6-935c-d1c659f889af.png">

I believe this is because it parses the code and anything after req.body. is recognised as a parameter. In the API code, when I use req.body.hasOwnProperty("property_name"), it incorrectly reads hasOwnProperty as a body parameter. Can you please help me solve this issue?

Thanks in advance!

**Comment by davibaltar** [comment]
Hi @irzakamran99! Thank you for opening the issue. 

I'll try to fix this in the next version.

**Comment by irzakamran99** [comment]
Thanks a lot, Davi! Please take a look at [this issue](https://github.com/davibaltar/swagger-autogen/issues/99) too.

**Comment by davibaltar** [comment]
The version 2.12.7 has fixed this. If the problem persists, let me know.
