### ISSUE TITLE
Openapi 3.X format ( requestbody and response)

### ISSUE THREAD

**Issue by wang-chi** [davibaltar/swagger-autogen#97]
Hi,
I survey the latest project version and have some suggestions related to data format.
Under openapi 3.X, 
there provide 

on `responses body` both two forms
1) can config content type
```
    /* #swagger.responses[200] = {
            content: {
                "application/json": {
                    schema: { "$ref": "#/definitions/success" },
                    examples:{
                        success: { "$ref": "#/components/examples/success" }
                    }
                }
            }
        }
    */
```

2) auto generate two type (json/xml)
```
    /* #swagger.responses[200] = {
            schema: { "$ref": "#/definitions/success" },
            examples:{
                success: { "$ref": "#/components/examples/success" }
            }
        }
    */
```

However, on `request body` only can accept the first form.
1) need to config the type of content
```
    /* #swagger.requestBody = {
            required: true,
            content: {
                "application/json": {
                    schema: { $ref: "#/definitions/sample" }
                }
            }
        }
    */
```

2) this one is not working, can not generate two content

```
    /* #swagger.requestBody = {
            required: true,
            schema: { $ref: "#/definitions/sample" }
        }
    */
```

I think that the request body also can accept two forms is more convenient.

Then, 
due to force conversion, the code looks like a little weird.
some parts uses `#/definitions/XXX`, some parts use `#/components/examples/XXX`

**Comment by davibaltar** [comment]
Hi @wang-chi! Thank you for opening the issue. 

Good note! It is a good idea to accept these two forms. 

And for this case:

```js
 /* #swagger.requestBody = {
            required: true,
            schema: { $ref: "#/definitions/sample" }
    }
 */
```

how the "content"  is missing, I'm thinking in add `content: "application/json"` automatically by default in the .json file. I'm going to try to add this feature in the next versions. 

Any other observation, let me know! 
Thanks!

**Comment by momega** [comment]
+1

**Comment by davibaltar** [comment]
The version 2.21.0 has implemented this and the documentation was updated: [https://github.com/davibaltar/swagger-autogen#request-body](https://github.com/davibaltar/swagger-autogen#request-body)
